// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const countChunksByDocumentID = `-- name: CountChunksByDocumentID :one
SELECT count(*) FROM chunks WHERE document_id = $1 AND workspace_hash = $2
`

type CountChunksByDocumentIDParams struct {
	DocumentID    uuid.UUID
	WorkspaceHash string
}

func (q *Queries) CountChunksByDocumentID(ctx context.Context, arg CountChunksByDocumentIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChunksByDocumentID, arg.DocumentID, arg.WorkspaceHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteChunksByDocumentID = `-- name: DeleteChunksByDocumentID :exec
DELETE FROM chunks WHERE document_id = $1 AND workspace_hash = $2
`

type DeleteChunksByDocumentIDParams struct {
	DocumentID    uuid.UUID
	WorkspaceHash string
}

func (q *Queries) DeleteChunksByDocumentID(ctx context.Context, arg DeleteChunksByDocumentIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteChunksByDocumentID, arg.DocumentID, arg.WorkspaceHash)
	return err
}

const deleteChunksByIDs = `-- name: DeleteChunksByIDs :exec
DELETE FROM chunks WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteChunksByIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChunksByIDs, pq.Array(dollar_1))
	return err
}

const getChunkByID = `-- name: GetChunkByID :one
SELECT c.id, c.document_id, c.workspace_hash, c.content_hash, c.content, c.chunk_index, c.start_line, c.end_line, c.metadata, c.embed_status, c.created_at,
       COALESCE(d.source_path, '') AS source_path
FROM chunks c
LEFT JOIN documents d ON d.id = c.document_id
WHERE c.id = $1
`

type GetChunkByIDRow struct {
	ID            uuid.UUID
	DocumentID    uuid.UUID
	WorkspaceHash string
	ContentHash   string
	Content       string
	ChunkIndex    int32
	StartLine     sql.NullInt32
	EndLine       sql.NullInt32
	Metadata      pqtype.NullRawMessage
	EmbedStatus   string
	CreatedAt     time.Time
	SourcePath    string
}

func (q *Queries) GetChunkByID(ctx context.Context, id uuid.UUID) (GetChunkByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getChunkByID, id)
	var i GetChunkByIDRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.WorkspaceHash,
		&i.ContentHash,
		&i.Content,
		&i.ChunkIndex,
		&i.StartLine,
		&i.EndLine,
		&i.Metadata,
		&i.EmbedStatus,
		&i.CreatedAt,
		&i.SourcePath,
	)
	return i, err
}

const listChunksByDocumentID = `-- name: ListChunksByDocumentID :many
SELECT id, document_id, workspace_hash, content_hash, content, chunk_index, start_line, end_line, metadata, created_at
FROM chunks WHERE document_id = $1 AND workspace_hash = $2 ORDER BY chunk_index
`

type ListChunksByDocumentIDParams struct {
	DocumentID    uuid.UUID
	WorkspaceHash string
}

type ListChunksByDocumentIDRow struct {
	ID            uuid.UUID
	DocumentID    uuid.UUID
	WorkspaceHash string
	ContentHash   string
	Content       string
	ChunkIndex    int32
	StartLine     sql.NullInt32
	EndLine       sql.NullInt32
	Metadata      pqtype.NullRawMessage
	CreatedAt     time.Time
}

func (q *Queries) ListChunksByDocumentID(ctx context.Context, arg ListChunksByDocumentIDParams) ([]ListChunksByDocumentIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listChunksByDocumentID, arg.DocumentID, arg.WorkspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChunksByDocumentIDRow
	for rows.Next() {
		var i ListChunksByDocumentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.WorkspaceHash,
			&i.ContentHash,
			&i.Content,
			&i.ChunkIndex,
			&i.StartLine,
			&i.EndLine,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChunk = `-- name: UpsertChunk :one
INSERT INTO chunks (document_id, workspace_hash, content_hash, content, chunk_index, start_line, end_line, metadata, symbol_name, symbol_kind, language, line_start, line_end, chunk_type, embedding_strategy)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (content_hash, workspace_hash, document_id) DO UPDATE SET
    document_id = EXCLUDED.document_id,
    content = EXCLUDED.content,
    chunk_index = EXCLUDED.chunk_index,
    start_line = EXCLUDED.start_line,
    end_line = EXCLUDED.end_line,
    metadata = EXCLUDED.metadata,
    symbol_name = EXCLUDED.symbol_name,
    symbol_kind = EXCLUDED.symbol_kind,
    language = EXCLUDED.language,
    line_start = EXCLUDED.line_start,
    line_end = EXCLUDED.line_end,
    chunk_type = EXCLUDED.chunk_type,
    embedding_strategy = EXCLUDED.embedding_strategy,
    embed_status = CASE 
        WHEN EXCLUDED.content != chunks.content THEN 'pending'
        ELSE chunks.embed_status
    END
RETURNING id
`

type UpsertChunkParams struct {
	DocumentID        uuid.UUID
	WorkspaceHash     string
	ContentHash       string
	Content           string
	ChunkIndex        int32
	StartLine         sql.NullInt32
	EndLine           sql.NullInt32
	Metadata          pqtype.NullRawMessage
	SymbolName        sql.NullString
	SymbolKind        sql.NullString
	Language          sql.NullString
	LineStart         sql.NullInt32
	LineEnd           sql.NullInt32
	ChunkType         string
	EmbeddingStrategy string
}

func (q *Queries) UpsertChunk(ctx context.Context, arg UpsertChunkParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, upsertChunk,
		arg.DocumentID,
		arg.WorkspaceHash,
		arg.ContentHash,
		arg.Content,
		arg.ChunkIndex,
		arg.StartLine,
		arg.EndLine,
		arg.Metadata,
		arg.SymbolName,
		arg.SymbolKind,
		arg.Language,
		arg.LineStart,
		arg.LineEnd,
		arg.ChunkType,
		arg.EmbeddingStrategy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
