// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: code_summarization.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const bulkGetCalleeNodes = `-- name: BulkGetCalleeNodes :many
SELECT DISTINCT source_node, target_node
FROM graph_edges
WHERE workspace_hash = $1
  AND source_node = ANY($2::text[])
  AND edge_type = 'calls'
`

type BulkGetCalleeNodesParams struct {
	WorkspaceHash string
	Column2       []string
}

type BulkGetCalleeNodesRow struct {
	SourceNode string
	TargetNode string
}

func (q *Queries) BulkGetCalleeNodes(ctx context.Context, arg BulkGetCalleeNodesParams) ([]BulkGetCalleeNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, bulkGetCalleeNodes, arg.WorkspaceHash, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BulkGetCalleeNodesRow
	for rows.Next() {
		var i BulkGetCalleeNodesRow
		if err := rows.Scan(&i.SourceNode, &i.TargetNode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bulkGetCallerContext = `-- name: BulkGetCallerContext :many
SELECT target_node, source_node, COUNT(*)::int AS frequency
FROM graph_edges
WHERE workspace_hash = $1
  AND target_node = ANY($2::text[])
  AND edge_type = 'calls'
GROUP BY target_node, source_node
ORDER BY target_node, frequency DESC
`

type BulkGetCallerContextParams struct {
	WorkspaceHash string
	Column2       []string
}

type BulkGetCallerContextRow struct {
	TargetNode string
	SourceNode string
	Frequency  int32
}

func (q *Queries) BulkGetCallerContext(ctx context.Context, arg BulkGetCallerContextParams) ([]BulkGetCallerContextRow, error) {
	rows, err := q.db.QueryContext(ctx, bulkGetCallerContext, arg.WorkspaceHash, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BulkGetCallerContextRow
	for rows.Next() {
		var i BulkGetCallerContextRow
		if err := rows.Scan(&i.TargetNode, &i.SourceNode, &i.Frequency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCodeSummarizationFailuresByWorkspace = `-- name: DeleteCodeSummarizationFailuresByWorkspace :exec
DELETE FROM code_summarization_failures WHERE workspace_hash = $1
`

func (q *Queries) DeleteCodeSummarizationFailuresByWorkspace(ctx context.Context, workspaceHash string) error {
	_, err := q.db.ExecContext(ctx, deleteCodeSummarizationFailuresByWorkspace, workspaceHash)
	return err
}

const deleteCodeSummarizationUsageByWorkspace = `-- name: DeleteCodeSummarizationUsageByWorkspace :exec
DELETE FROM code_summarization_usage WHERE workspace_hash = $1
`

func (q *Queries) DeleteCodeSummarizationUsageByWorkspace(ctx context.Context, workspaceHash string) error {
	_, err := q.db.ExecContext(ctx, deleteCodeSummarizationUsageByWorkspace, workspaceHash)
	return err
}

const getCalleeNodes = `-- name: GetCalleeNodes :many
SELECT DISTINCT target_node
FROM graph_edges
WHERE workspace_hash = $1
  AND source_node = $2
  AND edge_type = 'calls'
`

type GetCalleeNodesParams struct {
	WorkspaceHash string
	SourceNode    string
}

func (q *Queries) GetCalleeNodes(ctx context.Context, arg GetCalleeNodesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCalleeNodes, arg.WorkspaceHash, arg.SourceNode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var target_node string
		if err := rows.Scan(&target_node); err != nil {
			return nil, err
		}
		items = append(items, target_node)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCodeSummarizationUsage = `-- name: GetCodeSummarizationUsage :one
SELECT request_count FROM code_summarization_usage
WHERE workspace_hash = $1 AND usage_date = CURRENT_DATE
`

func (q *Queries) GetCodeSummarizationUsage(ctx context.Context, workspaceHash string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCodeSummarizationUsage, workspaceHash)
	var request_count int32
	err := row.Scan(&request_count)
	return request_count, err
}

const getFailureBySymbol = `-- name: GetFailureBySymbol :one
SELECT id, attempts FROM code_summarization_failures
WHERE workspace_hash = $1 AND content_hash = $2 AND resolved_at IS NULL
LIMIT 1
`

type GetFailureBySymbolParams struct {
	WorkspaceHash string
	ContentHash   string
}

type GetFailureBySymbolRow struct {
	ID       uuid.UUID
	Attempts int32
}

func (q *Queries) GetFailureBySymbol(ctx context.Context, arg GetFailureBySymbolParams) (GetFailureBySymbolRow, error) {
	row := q.db.QueryRowContext(ctx, getFailureBySymbol, arg.WorkspaceHash, arg.ContentHash)
	var i GetFailureBySymbolRow
	err := row.Scan(&i.ID, &i.Attempts)
	return i, err
}

const getSummarizationStatus = `-- name: GetSummarizationStatus :one
SELECT
    (SELECT COUNT(*) FROM chunks c WHERE c.workspace_hash = $1 AND c.chunk_type = 'symbol' AND c.symbol_name IS NOT NULL)::int AS total_symbols,
    (SELECT COUNT(*) FROM documents d WHERE d.workspace_hash = $1 AND d.tags @> ARRAY['symbol-summary'])::int AS summarized,
    (SELECT COUNT(*) FROM code_summarization_failures csf WHERE csf.workspace_hash = $1 AND csf.resolved_at IS NULL)::int AS failed
`

type GetSummarizationStatusRow struct {
	TotalSymbols int32
	Summarized   int32
	Failed       int32
}

func (q *Queries) GetSummarizationStatus(ctx context.Context, workspaceHash string) (GetSummarizationStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getSummarizationStatus, workspaceHash)
	var i GetSummarizationStatusRow
	err := row.Scan(&i.TotalSymbols, &i.Summarized, &i.Failed)
	return i, err
}

const getSymbolChunksByGraphContextStale = `-- name: GetSymbolChunksByGraphContextStale :many
SELECT
    c.id,
    c.content,
    c.symbol_name,
    c.symbol_kind,
    c.language,
    c.content_hash,
    c.graph_context_hash,
    COALESCE(d.source_path, '') AS source_path
FROM chunks c
LEFT JOIN documents d ON d.id = c.document_id
WHERE c.workspace_hash = $1
  AND c.chunk_type = 'symbol'
  AND c.symbol_name IS NOT NULL
  AND c.symbol_name != ''
  AND c.graph_context_hash IS NULL
  AND EXISTS (
      SELECT 1
      FROM documents doc
      WHERE doc.workspace_hash = c.workspace_hash
        AND doc.tags @> ARRAY['symbol-summary']::text[]
        AND doc.metadata->>'source_content_hash' = c.content_hash
  )
LIMIT $2
`

type GetSymbolChunksByGraphContextStaleParams struct {
	WorkspaceHash string
	Limit         int32
}

type GetSymbolChunksByGraphContextStaleRow struct {
	ID               uuid.UUID
	Content          string
	SymbolName       sql.NullString
	SymbolKind       sql.NullString
	Language         sql.NullString
	ContentHash      string
	GraphContextHash sql.NullString
	SourcePath       string
}

func (q *Queries) GetSymbolChunksByGraphContextStale(ctx context.Context, arg GetSymbolChunksByGraphContextStaleParams) ([]GetSymbolChunksByGraphContextStaleRow, error) {
	rows, err := q.db.QueryContext(ctx, getSymbolChunksByGraphContextStale, arg.WorkspaceHash, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSymbolChunksByGraphContextStaleRow
	for rows.Next() {
		var i GetSymbolChunksByGraphContextStaleRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SymbolName,
			&i.SymbolKind,
			&i.Language,
			&i.ContentHash,
			&i.GraphContextHash,
			&i.SourcePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnresolvedFailures = `-- name: GetUnresolvedFailures :many
SELECT id, workspace_hash, symbol_name, symbol_kind, source_file, content_hash, error_reason, error_type, attempts, last_attempt_at, created_at
FROM code_summarization_failures
WHERE workspace_hash = $1 AND resolved_at IS NULL
ORDER BY last_attempt_at DESC
`

type GetUnresolvedFailuresRow struct {
	ID            uuid.UUID
	WorkspaceHash string
	SymbolName    string
	SymbolKind    sql.NullString
	SourceFile    string
	ContentHash   string
	ErrorReason   string
	ErrorType     string
	Attempts      int32
	LastAttemptAt time.Time
	CreatedAt     time.Time
}

func (q *Queries) GetUnresolvedFailures(ctx context.Context, workspaceHash string) ([]GetUnresolvedFailuresRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnresolvedFailures, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnresolvedFailuresRow
	for rows.Next() {
		var i GetUnresolvedFailuresRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceHash,
			&i.SymbolName,
			&i.SymbolKind,
			&i.SourceFile,
			&i.ContentHash,
			&i.ErrorReason,
			&i.ErrorType,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnsummarizedSymbols = `-- name: GetUnsummarizedSymbols :many
SELECT 
    c.id,
    c.content,
    c.symbol_name,
    c.symbol_kind,
    c.language,
    c.content_hash,
    COALESCE(d.source_path, '') AS source_path
FROM chunks c
LEFT JOIN documents d ON d.id = c.document_id
WHERE c.workspace_hash = $1
  AND c.chunk_type = 'symbol'
  AND c.symbol_name IS NOT NULL
  AND c.symbol_name != ''
  AND NOT EXISTS (
      SELECT 1
      FROM documents doc
      WHERE doc.workspace_hash = c.workspace_hash
        AND doc.tags @> ARRAY['symbol-summary']::text[]
        AND doc.metadata->>'source_content_hash' = c.content_hash
  )
LIMIT $2
`

type GetUnsummarizedSymbolsParams struct {
	WorkspaceHash string
	Limit         int32
}

type GetUnsummarizedSymbolsRow struct {
	ID          uuid.UUID
	Content     string
	SymbolName  sql.NullString
	SymbolKind  sql.NullString
	Language    sql.NullString
	ContentHash string
	SourcePath  string
}

func (q *Queries) GetUnsummarizedSymbols(ctx context.Context, arg GetUnsummarizedSymbolsParams) ([]GetUnsummarizedSymbolsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnsummarizedSymbols, arg.WorkspaceHash, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnsummarizedSymbolsRow
	for rows.Next() {
		var i GetUnsummarizedSymbolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SymbolName,
			&i.SymbolKind,
			&i.Language,
			&i.ContentHash,
			&i.SourcePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementCodeSummarizationUsage = `-- name: IncrementCodeSummarizationUsage :exec
INSERT INTO code_summarization_usage (workspace_hash, usage_date, request_count)
VALUES ($1, CURRENT_DATE, 1)
ON CONFLICT (workspace_hash, usage_date) DO UPDATE
SET request_count = code_summarization_usage.request_count + 1
`

func (q *Queries) IncrementCodeSummarizationUsage(ctx context.Context, workspaceHash string) error {
	_, err := q.db.ExecContext(ctx, incrementCodeSummarizationUsage, workspaceHash)
	return err
}

const nullifyGraphContextHashBySymbols = `-- name: NullifyGraphContextHashBySymbols :exec
UPDATE chunks SET graph_context_hash = NULL
WHERE workspace_hash = $1
  AND chunk_type = 'symbol'
  AND symbol_name = ANY($2::text[])
`

type NullifyGraphContextHashBySymbolsParams struct {
	WorkspaceHash string
	Column2       []string
}

func (q *Queries) NullifyGraphContextHashBySymbols(ctx context.Context, arg NullifyGraphContextHashBySymbolsParams) error {
	_, err := q.db.ExecContext(ctx, nullifyGraphContextHashBySymbols, arg.WorkspaceHash, pq.Array(arg.Column2))
	return err
}

const resolveFailure = `-- name: ResolveFailure :exec
UPDATE code_summarization_failures
SET resolved_at = NOW()
WHERE id = $1
`

func (q *Queries) ResolveFailure(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resolveFailure, id)
	return err
}

const updateChunkGraphContextHash = `-- name: UpdateChunkGraphContextHash :exec
UPDATE chunks SET graph_context_hash = $2
WHERE id = $1
`

type UpdateChunkGraphContextHashParams struct {
	ID               uuid.UUID
	GraphContextHash sql.NullString
}

func (q *Queries) UpdateChunkGraphContextHash(ctx context.Context, arg UpdateChunkGraphContextHashParams) error {
	_, err := q.db.ExecContext(ctx, updateChunkGraphContextHash, arg.ID, arg.GraphContextHash)
	return err
}

const updateCodeSummarizationFailure = `-- name: UpdateCodeSummarizationFailure :exec
UPDATE code_summarization_failures
SET attempts = $2, error_reason = $3, last_attempt_at = NOW()
WHERE id = $1
`

type UpdateCodeSummarizationFailureParams struct {
	ID          uuid.UUID
	Attempts    int32
	ErrorReason string
}

func (q *Queries) UpdateCodeSummarizationFailure(ctx context.Context, arg UpdateCodeSummarizationFailureParams) error {
	_, err := q.db.ExecContext(ctx, updateCodeSummarizationFailure, arg.ID, arg.Attempts, arg.ErrorReason)
	return err
}

const upsertCodeSummarizationFailure = `-- name: UpsertCodeSummarizationFailure :exec
INSERT INTO code_summarization_failures (workspace_hash, symbol_name, symbol_kind, source_file, content_hash, error_reason, error_type, attempts, last_attempt_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 1, NOW())
ON CONFLICT (workspace_hash, content_hash) WHERE resolved_at IS NULL
DO UPDATE SET
    attempts = code_summarization_failures.attempts + 1,
    error_reason = EXCLUDED.error_reason,
    error_type = EXCLUDED.error_type,
    last_attempt_at = NOW()
`

type UpsertCodeSummarizationFailureParams struct {
	WorkspaceHash string
	SymbolName    string
	SymbolKind    sql.NullString
	SourceFile    string
	ContentHash   string
	ErrorReason   string
	ErrorType     string
}

func (q *Queries) UpsertCodeSummarizationFailure(ctx context.Context, arg UpsertCodeSummarizationFailureParams) error {
	_, err := q.db.ExecContext(ctx, upsertCodeSummarizationFailure,
		arg.WorkspaceHash,
		arg.SymbolName,
		arg.SymbolKind,
		arg.SourceFile,
		arg.ContentHash,
		arg.ErrorReason,
		arg.ErrorType,
	)
	return err
}
