// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: code_summarization.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getCodeSummarizationUsage = `-- name: GetCodeSummarizationUsage :one
SELECT request_count FROM code_summarization_usage
WHERE workspace_hash = $1 AND usage_date = CURRENT_DATE
`

func (q *Queries) GetCodeSummarizationUsage(ctx context.Context, workspaceHash string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCodeSummarizationUsage, workspaceHash)
	var request_count int32
	err := row.Scan(&request_count)
	return request_count, err
}

const getUnsummarizedSymbols = `-- name: GetUnsummarizedSymbols :many
SELECT 
    c.id,
    c.content,
    c.symbol_name,
    c.symbol_kind,
    c.language,
    c.content_hash,
    COALESCE(d.source_path, '') AS source_path
FROM chunks c
LEFT JOIN documents d ON d.id = c.document_id
WHERE c.workspace_hash = $1
  AND c.chunk_type = 'symbol'
  AND c.symbol_name IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM documents doc
      WHERE doc.workspace_hash = c.workspace_hash
        AND doc.tags @> ARRAY['symbol-summary']::text[]
        AND doc.metadata->>'source_content_hash' = c.content_hash
  )
LIMIT $2
`

type GetUnsummarizedSymbolsParams struct {
	WorkspaceHash string
	Limit         int32
}

type GetUnsummarizedSymbolsRow struct {
	ID          uuid.UUID
	Content     string
	SymbolName  sql.NullString
	SymbolKind  sql.NullString
	Language    sql.NullString
	ContentHash string
	SourcePath  string
}

func (q *Queries) GetUnsummarizedSymbols(ctx context.Context, arg GetUnsummarizedSymbolsParams) ([]GetUnsummarizedSymbolsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnsummarizedSymbols, arg.WorkspaceHash, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnsummarizedSymbolsRow
	for rows.Next() {
		var i GetUnsummarizedSymbolsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SymbolName,
			&i.SymbolKind,
			&i.Language,
			&i.ContentHash,
			&i.SourcePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementCodeSummarizationUsage = `-- name: IncrementCodeSummarizationUsage :exec
INSERT INTO code_summarization_usage (workspace_hash, usage_date, request_count)
VALUES ($1, CURRENT_DATE, 1)
ON CONFLICT (workspace_hash, usage_date) DO UPDATE
SET request_count = code_summarization_usage.request_count + 1
`

func (q *Queries) IncrementCodeSummarizationUsage(ctx context.Context, workspaceHash string) error {
	_, err := q.db.ExecContext(ctx, incrementCodeSummarizationUsage, workspaceHash)
	return err
}
