// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countDocumentsByCollection = `-- name: CountDocumentsByCollection :one
SELECT count(*) FROM documents WHERE collection = $1 AND workspace_hash = $2
`

type CountDocumentsByCollectionParams struct {
	Collection    string
	WorkspaceHash string
}

func (q *Queries) CountDocumentsByCollection(ctx context.Context, arg CountDocumentsByCollectionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocumentsByCollection, arg.Collection, arg.WorkspaceHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE name = $1 AND workspace_hash = $2
`

type DeleteCollectionParams struct {
	Name          string
	WorkspaceHash string
}

func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteCollection, arg.Name, arg.WorkspaceHash)
	return err
}

const getCollectionByName = `-- name: GetCollectionByName :one
SELECT id, workspace_hash, name, path, glob_pattern, update_mode, exclude_patterns, created_at, updated_at, allowed_extensions FROM collections WHERE name = $1 AND workspace_hash = $2
`

type GetCollectionByNameParams struct {
	Name          string
	WorkspaceHash string
}

func (q *Queries) GetCollectionByName(ctx context.Context, arg GetCollectionByNameParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollectionByName, arg.Name, arg.WorkspaceHash)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceHash,
		&i.Name,
		&i.Path,
		&i.GlobPattern,
		&i.UpdateMode,
		pq.Array(&i.ExcludePatterns),
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.AllowedExtensions),
	)
	return i, err
}

const listCollections = `-- name: ListCollections :many
SELECT id, workspace_hash, name, path, glob_pattern, update_mode, exclude_patterns, created_at, updated_at, allowed_extensions FROM collections WHERE workspace_hash = $1 ORDER BY name
`

func (q *Queries) ListCollections(ctx context.Context, workspaceHash string) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listCollections, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceHash,
			&i.Name,
			&i.Path,
			&i.GlobPattern,
			&i.UpdateMode,
			pq.Array(&i.ExcludePatterns),
			&i.CreatedAt,
			&i.UpdatedAt,
			pq.Array(&i.AllowedExtensions),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsWithDocCount = `-- name: ListCollectionsWithDocCount :many
SELECT c.id, c.workspace_hash, c.name, c.path, c.glob_pattern, c.update_mode, c.exclude_patterns, c.allowed_extensions, c.created_at, c.updated_at, COALESCE(d.cnt, 0)::bigint AS document_count
FROM collections c
LEFT JOIN (
    SELECT collection, workspace_hash, count(*) AS cnt
    FROM documents
    GROUP BY collection, workspace_hash
) d ON c.name = d.collection AND c.workspace_hash = d.workspace_hash
WHERE c.workspace_hash = $1
ORDER BY c.name
`

type ListCollectionsWithDocCountRow struct {
	ID                uuid.UUID
	WorkspaceHash     string
	Name              string
	Path              string
	GlobPattern       string
	UpdateMode        string
	ExcludePatterns   []string
	AllowedExtensions []string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DocumentCount     int64
}

func (q *Queries) ListCollectionsWithDocCount(ctx context.Context, workspaceHash string) ([]ListCollectionsWithDocCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionsWithDocCount, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectionsWithDocCountRow
	for rows.Next() {
		var i ListCollectionsWithDocCountRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceHash,
			&i.Name,
			&i.Path,
			&i.GlobPattern,
			&i.UpdateMode,
			pq.Array(&i.ExcludePatterns),
			pq.Array(&i.AllowedExtensions),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCollection = `-- name: RenameCollection :one
UPDATE collections SET name = $2, updated_at = now()
WHERE name = $1 AND workspace_hash = $3
RETURNING id, workspace_hash, name, path, glob_pattern, update_mode, exclude_patterns, created_at, updated_at, allowed_extensions
`

type RenameCollectionParams struct {
	Name          string
	Name_2        string
	WorkspaceHash string
}

func (q *Queries) RenameCollection(ctx context.Context, arg RenameCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, renameCollection, arg.Name, arg.Name_2, arg.WorkspaceHash)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceHash,
		&i.Name,
		&i.Path,
		&i.GlobPattern,
		&i.UpdateMode,
		pq.Array(&i.ExcludePatterns),
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.AllowedExtensions),
	)
	return i, err
}

const upsertCollection = `-- name: UpsertCollection :one
INSERT INTO collections (workspace_hash, name, path, glob_pattern, update_mode)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (name, workspace_hash) DO UPDATE SET
    path = EXCLUDED.path,
    glob_pattern = EXCLUDED.glob_pattern,
    update_mode = EXCLUDED.update_mode,
    updated_at = now()
RETURNING id, workspace_hash, name, path, glob_pattern, update_mode, exclude_patterns, created_at, updated_at, allowed_extensions
`

type UpsertCollectionParams struct {
	WorkspaceHash string
	Name          string
	Path          string
	GlobPattern   string
	UpdateMode    string
}

func (q *Queries) UpsertCollection(ctx context.Context, arg UpsertCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, upsertCollection,
		arg.WorkspaceHash,
		arg.Name,
		arg.Path,
		arg.GlobPattern,
		arg.UpdateMode,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceHash,
		&i.Name,
		&i.Path,
		&i.GlobPattern,
		&i.UpdateMode,
		pq.Array(&i.ExcludePatterns),
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.AllowedExtensions),
	)
	return i, err
}
