// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package sqlc

import (
	"context"

	"github.com/lib/pq"
)

const listCollections = `-- name: ListCollections :many
SELECT id, workspace_hash, name, path, glob_pattern, update_mode, exclude_patterns, created_at, updated_at FROM collections WHERE workspace_hash = $1 ORDER BY name
`

func (q *Queries) ListCollections(ctx context.Context, workspaceHash string) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listCollections, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceHash,
			&i.Name,
			&i.Path,
			&i.GlobPattern,
			&i.UpdateMode,
			pq.Array(&i.ExcludePatterns),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCollection = `-- name: UpsertCollection :one
INSERT INTO collections (workspace_hash, name, path, glob_pattern, update_mode)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (name, workspace_hash) DO UPDATE SET
    path = EXCLUDED.path,
    glob_pattern = EXCLUDED.glob_pattern,
    update_mode = EXCLUDED.update_mode,
    updated_at = now()
RETURNING id, workspace_hash, name, path, glob_pattern, update_mode, exclude_patterns, created_at, updated_at
`

type UpsertCollectionParams struct {
	WorkspaceHash string
	Name          string
	Path          string
	GlobPattern   string
	UpdateMode    string
}

func (q *Queries) UpsertCollection(ctx context.Context, arg UpsertCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, upsertCollection,
		arg.WorkspaceHash,
		arg.Name,
		arg.Path,
		arg.GlobPattern,
		arg.UpdateMode,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceHash,
		&i.Name,
		&i.Path,
		&i.GlobPattern,
		&i.UpdateMode,
		pq.Array(&i.ExcludePatterns),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
