// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const countStaleRawOpenCodeDocs = `-- name: CountStaleRawOpenCodeDocs :one
SELECT COUNT(*)::int AS n
FROM documents d_raw
WHERE d_raw.source_path LIKE 'opencode://session/%'
  AND d_raw.collection = 'sessions'
  AND EXISTS (
    SELECT 1 FROM documents d_summary
    WHERE d_summary.source_path = 'summary://opencode/' || split_part(d_raw.source_path, '/', 4)
      AND d_summary.workspace_hash = d_raw.workspace_hash
      AND d_summary.collection = 'sessions'
  )
`

// Post-unification (phase 8), raw and summary session docs both live in
// collection 'sessions' and are distinguished by source_path scheme:
// raw = 'opencode://session/%', summary = 'summary://%'.
func (q *Queries) CountStaleRawOpenCodeDocs(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, countStaleRawOpenCodeDocs)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const deleteDocumentByIDAndWorkspace = `-- name: DeleteDocumentByIDAndWorkspace :execrows
DELETE FROM documents WHERE id = $1 AND workspace_hash = $2
`

type DeleteDocumentByIDAndWorkspaceParams struct {
	ID            uuid.UUID
	WorkspaceHash string
}

func (q *Queries) DeleteDocumentByIDAndWorkspace(ctx context.Context, arg DeleteDocumentByIDAndWorkspaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDocumentByIDAndWorkspace, arg.ID, arg.WorkspaceHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDocumentsByWorkspace = `-- name: DeleteDocumentsByWorkspace :exec
DELETE FROM documents WHERE workspace_hash = $1
`

func (q *Queries) DeleteDocumentsByWorkspace(ctx context.Context, workspaceHash string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentsByWorkspace, workspaceHash)
	return err
}

const deleteFlowDocumentsByWorkspace = `-- name: DeleteFlowDocumentsByWorkspace :exec
DELETE FROM documents
WHERE workspace_hash = $1
  AND collection = 'flows'
`

func (q *Queries) DeleteFlowDocumentsByWorkspace(ctx context.Context, workspaceHash string) error {
	_, err := q.db.ExecContext(ctx, deleteFlowDocumentsByWorkspace, workspaceHash)
	return err
}

const deleteStaleRawOpenCodeDocs = `-- name: DeleteStaleRawOpenCodeDocs :execrows
DELETE FROM documents d_raw
WHERE d_raw.source_path LIKE 'opencode://session/%'
  AND d_raw.collection = 'sessions'
  AND EXISTS (
    SELECT 1 FROM documents d_summary
    WHERE d_summary.source_path = 'summary://opencode/' || split_part(d_raw.source_path, '/', 4)
      AND d_summary.workspace_hash = d_raw.workspace_hash
      AND d_summary.collection = 'sessions'
  )
`

func (q *Queries) DeleteStaleRawOpenCodeDocs(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStaleRawOpenCodeDocs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSymbolDocumentsByCollection = `-- name: DeleteSymbolDocumentsByCollection :exec
DELETE FROM documents
WHERE workspace_hash = $1
  AND collection = $2
  AND metadata->>'source_type' = 'symbol'
`

type DeleteSymbolDocumentsByCollectionParams struct {
	WorkspaceHash string
	Collection    string
}

func (q *Queries) DeleteSymbolDocumentsByCollection(ctx context.Context, arg DeleteSymbolDocumentsByCollectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSymbolDocumentsByCollection, arg.WorkspaceHash, arg.Collection)
	return err
}

const getDocumentByHash = `-- name: GetDocumentByHash :one
SELECT id, workspace_hash, content_hash, title, content, source_path, collection, tags, metadata, created_at, updated_at, supersedes_id, mod_time, file_size FROM documents WHERE content_hash = $1 AND workspace_hash = $2
`

type GetDocumentByHashParams struct {
	ContentHash   string
	WorkspaceHash string
}

func (q *Queries) GetDocumentByHash(ctx context.Context, arg GetDocumentByHashParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByHash, arg.ContentHash, arg.WorkspaceHash)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceHash,
		&i.ContentHash,
		&i.Title,
		&i.Content,
		&i.SourcePath,
		&i.Collection,
		pq.Array(&i.Tags),
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupersedesID,
		&i.ModTime,
		&i.FileSize,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, workspace_hash, content_hash, title, content, source_path, collection, tags, metadata, created_at, updated_at, supersedes_id, mod_time, file_size FROM documents WHERE id = $1 AND workspace_hash = $2
`

type GetDocumentByIDParams struct {
	ID            uuid.UUID
	WorkspaceHash string
}

func (q *Queries) GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, arg.ID, arg.WorkspaceHash)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceHash,
		&i.ContentHash,
		&i.Title,
		&i.Content,
		&i.SourcePath,
		&i.Collection,
		pq.Array(&i.Tags),
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupersedesID,
		&i.ModTime,
		&i.FileSize,
	)
	return i, err
}

const getDocumentBySourcePath = `-- name: GetDocumentBySourcePath :one
SELECT id, workspace_hash, content_hash, title, content, source_path, collection, tags, metadata, created_at, updated_at, supersedes_id, mod_time, file_size FROM documents WHERE source_path = $1 AND workspace_hash = $2
`

type GetDocumentBySourcePathParams struct {
	SourcePath    string
	WorkspaceHash string
}

func (q *Queries) GetDocumentBySourcePath(ctx context.Context, arg GetDocumentBySourcePathParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentBySourcePath, arg.SourcePath, arg.WorkspaceHash)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceHash,
		&i.ContentHash,
		&i.Title,
		&i.Content,
		&i.SourcePath,
		&i.Collection,
		pq.Array(&i.Tags),
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupersedesID,
		&i.ModTime,
		&i.FileSize,
	)
	return i, err
}

const listDocumentSourcePathsAndHashes = `-- name: ListDocumentSourcePathsAndHashes :many
SELECT id, source_path, content_hash
FROM documents
WHERE workspace_hash = $1
  AND collection = $2
  AND source_path != ''
ORDER BY source_path
`

type ListDocumentSourcePathsAndHashesParams struct {
	WorkspaceHash string
	Collection    string
}

type ListDocumentSourcePathsAndHashesRow struct {
	ID          uuid.UUID
	SourcePath  string
	ContentHash string
}

func (q *Queries) ListDocumentSourcePathsAndHashes(ctx context.Context, arg ListDocumentSourcePathsAndHashesParams) ([]ListDocumentSourcePathsAndHashesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentSourcePathsAndHashes, arg.WorkspaceHash, arg.Collection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentSourcePathsAndHashesRow
	for rows.Next() {
		var i ListDocumentSourcePathsAndHashesRow
		if err := rows.Scan(&i.ID, &i.SourcePath, &i.ContentHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByTag = `-- name: ListDocumentsByTag :many
SELECT id, workspace_hash, title, content, source_path, collection, tags, created_at, updated_at
FROM documents
WHERE $1::text = ANY(tags)
  AND collection = $2
ORDER BY updated_at DESC
LIMIT $3
`

type ListDocumentsByTagParams struct {
	Column1    string
	Collection string
	Limit      int32
}

type ListDocumentsByTagRow struct {
	ID            uuid.UUID
	WorkspaceHash string
	Title         string
	Content       string
	SourcePath    string
	Collection    string
	Tags          []string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Cross-workspace tag query: returns documents matching a single tag value
// across ALL workspaces. No workspace_hash filter — intentionally global.
func (q *Queries) ListDocumentsByTag(ctx context.Context, arg ListDocumentsByTagParams) ([]ListDocumentsByTagRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByTag, arg.Column1, arg.Collection, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByTagRow
	for rows.Next() {
		var i ListDocumentsByTagRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceHash,
			&i.Title,
			&i.Content,
			&i.SourcePath,
			&i.Collection,
			pq.Array(&i.Tags),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByWorkspace = `-- name: ListDocumentsByWorkspace :many
SELECT d.id, d.workspace_hash, d.content_hash, d.title, d.source_path, d.collection, d.tags, d.created_at, d.updated_at,
       d.supersedes_id,
       (SELECT s.id FROM documents s WHERE s.supersedes_id = d.id LIMIT 1) AS superseded_by_id
FROM documents d
WHERE d.workspace_hash = $1
ORDER BY d.updated_at DESC
`

type ListDocumentsByWorkspaceRow struct {
	ID             uuid.UUID
	WorkspaceHash  string
	ContentHash    string
	Title          string
	SourcePath     string
	Collection     string
	Tags           []string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	SupersedesID   uuid.NullUUID
	SupersededByID uuid.UUID
}

func (q *Queries) ListDocumentsByWorkspace(ctx context.Context, workspaceHash string) ([]ListDocumentsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByWorkspace, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByWorkspaceRow
	for rows.Next() {
		var i ListDocumentsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceHash,
			&i.ContentHash,
			&i.Title,
			&i.SourcePath,
			&i.Collection,
			pq.Array(&i.Tags),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SupersedesID,
			&i.SupersededByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionDocumentsByWorkspace = `-- name: ListSessionDocumentsByWorkspace :many
SELECT id, workspace_hash, content_hash, title, source_path, collection, tags, content, created_at, updated_at
FROM documents
WHERE workspace_hash = $1
  AND collection = 'sessions'
  AND ($2::text = '' OR $2::text = ANY(tags))
ORDER BY created_at DESC
LIMIT $3
`

type ListSessionDocumentsByWorkspaceParams struct {
	WorkspaceHash string
	TagFilter     string
	Lim           int32
}

type ListSessionDocumentsByWorkspaceRow struct {
	ID            uuid.UUID
	WorkspaceHash string
	ContentHash   string
	Title         string
	SourcePath    string
	Collection    string
	Tags          []string
	Content       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListSessionDocumentsByWorkspace(ctx context.Context, arg ListSessionDocumentsByWorkspaceParams) ([]ListSessionDocumentsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionDocumentsByWorkspace, arg.WorkspaceHash, arg.TagFilter, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionDocumentsByWorkspaceRow
	for rows.Next() {
		var i ListSessionDocumentsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceHash,
			&i.ContentHash,
			&i.Title,
			&i.SourcePath,
			&i.Collection,
			pq.Array(&i.Tags),
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSummaryDocumentsForBackfill = `-- name: ListSummaryDocumentsForBackfill :many
SELECT id, workspace_hash, content_hash, title, content, source_path, tags, metadata, created_at
FROM documents
WHERE collection = 'sessions'
  AND source_path LIKE 'summary://%'
  AND ($1::text = '' OR workspace_hash = $1)
  AND ($2::timestamptz IS NULL OR created_at >= $2)
ORDER BY created_at ASC
`

type ListSummaryDocumentsForBackfillParams struct {
	Column1 string
	Column2 time.Time
}

type ListSummaryDocumentsForBackfillRow struct {
	ID            uuid.UUID
	WorkspaceHash string
	ContentHash   string
	Title         string
	Content       string
	SourcePath    string
	Tags          []string
	Metadata      pqtype.NullRawMessage
	CreatedAt     time.Time
}

// Post-unification (phase 8), summary docs live in collection 'sessions' and
// are identified by the 'summary://%' source_path scheme (raw session docs in
// the same collection use 'opencode://%' / 'claude://%' schemes).
func (q *Queries) ListSummaryDocumentsForBackfill(ctx context.Context, arg ListSummaryDocumentsForBackfillParams) ([]ListSummaryDocumentsForBackfillRow, error) {
	rows, err := q.db.QueryContext(ctx, listSummaryDocumentsForBackfill, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSummaryDocumentsForBackfillRow
	for rows.Next() {
		var i ListSummaryDocumentsForBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceHash,
			&i.ContentHash,
			&i.Title,
			&i.Content,
			&i.SourcePath,
			pq.Array(&i.Tags),
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSymbolsByWorkspace = `-- name: ListSymbolsByWorkspace :many
SELECT id, workspace_hash, content_hash, title, source_path, collection, tags, metadata, created_at, updated_at
FROM documents
WHERE workspace_hash = $1
  AND metadata->>'source_type' = 'symbol'
  AND ($2::text = '' OR title ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR metadata->>'kind' = $3::text)
ORDER BY title
LIMIT $4
`

type ListSymbolsByWorkspaceParams struct {
	WorkspaceHash string
	Column2       string
	Column3       string
	Limit         int32
}

type ListSymbolsByWorkspaceRow struct {
	ID            uuid.UUID
	WorkspaceHash string
	ContentHash   string
	Title         string
	SourcePath    string
	Collection    string
	Tags          []string
	Metadata      pqtype.NullRawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListSymbolsByWorkspace(ctx context.Context, arg ListSymbolsByWorkspaceParams) ([]ListSymbolsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listSymbolsByWorkspace,
		arg.WorkspaceHash,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSymbolsByWorkspaceRow
	for rows.Next() {
		var i ListSymbolsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceHash,
			&i.ContentHash,
			&i.Title,
			&i.SourcePath,
			&i.Collection,
			pq.Array(&i.Tags),
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByWorkspace = `-- name: ListTagsByWorkspace :many
SELECT unnest(tags) AS tag, COUNT(*) AS count
FROM documents
WHERE workspace_hash = $1 AND tags IS NOT NULL AND array_length(tags, 1) > 0
GROUP BY tag
ORDER BY count DESC, tag
`

type ListTagsByWorkspaceRow struct {
	Tag   interface{}
	Count int64
}

func (q *Queries) ListTagsByWorkspace(ctx context.Context, workspaceHash string) ([]ListTagsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByWorkspace, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsByWorkspaceRow
	for rows.Next() {
		var i ListTagsByWorkspaceRow
		if err := rows.Scan(&i.Tag, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const preloadFileStateByWorkspace = `-- name: PreloadFileStateByWorkspace :many
SELECT source_path, mod_time, file_size, content_hash
FROM documents
WHERE workspace_hash = $1
  AND collection = $2
  AND source_path != ''
  AND mod_time IS NOT NULL
  AND file_size IS NOT NULL
`

type PreloadFileStateByWorkspaceParams struct {
	WorkspaceHash string
	Collection    string
}

type PreloadFileStateByWorkspaceRow struct {
	SourcePath  string
	ModTime     sql.NullTime
	FileSize    sql.NullInt64
	ContentHash string
}

// Returns the mtime+size fingerprint for all fully-fingerprinted documents in a
// workspace+collection. Used at watcher startup to warm the in-memory fast-path
// cache (plan 03). Rows with NULL mod_time or file_size are excluded — they were
// indexed before migration 00029 and must fall through to normal processing.
func (q *Queries) PreloadFileStateByWorkspace(ctx context.Context, arg PreloadFileStateByWorkspaceParams) ([]PreloadFileStateByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, preloadFileStateByWorkspace, arg.WorkspaceHash, arg.Collection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreloadFileStateByWorkspaceRow
	for rows.Next() {
		var i PreloadFileStateByWorkspaceRow
		if err := rows.Scan(
			&i.SourcePath,
			&i.ModTime,
			&i.FileSize,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentFileState = `-- name: UpdateDocumentFileState :exec
UPDATE documents
SET mod_time = $3, file_size = $4
WHERE source_path = $1 AND workspace_hash = $2
`

type UpdateDocumentFileStateParams struct {
	SourcePath    string
	WorkspaceHash string
	ModTime       sql.NullTime
	FileSize      sql.NullInt64
}

// Backfills the mtime+size fingerprint on the content-hash-match (dedup) path so
// the DB-warmed fast-path can skip this file on the next restart (999.1 Fix B
// gap: unchanged files — and rows indexed before migration 00029 — otherwise keep
// NULL mod_time/file_size forever and warmed stays 0). Touches only
// mod_time/file_size; title/content/updated_at are left intact so the
// documents_title_propagate trigger does not re-rank chunks.
func (q *Queries) UpdateDocumentFileState(ctx context.Context, arg UpdateDocumentFileStateParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentFileState,
		arg.SourcePath,
		arg.WorkspaceHash,
		arg.ModTime,
		arg.FileSize,
	)
	return err
}

const updateDocumentsCollection = `-- name: UpdateDocumentsCollection :exec
UPDATE documents SET collection = $2 WHERE collection = $1 AND workspace_hash = $3
`

type UpdateDocumentsCollectionParams struct {
	Collection    string
	Collection_2  string
	WorkspaceHash string
}

func (q *Queries) UpdateDocumentsCollection(ctx context.Context, arg UpdateDocumentsCollectionParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentsCollection, arg.Collection, arg.Collection_2, arg.WorkspaceHash)
	return err
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO documents (workspace_hash, content_hash, title, content, source_path, collection, tags, metadata, supersedes_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (source_path, workspace_hash) WHERE source_path != '' DO UPDATE SET
    content_hash = EXCLUDED.content_hash,
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    collection = EXCLUDED.collection,
    tags = EXCLUDED.tags,
    metadata = EXCLUDED.metadata,
    supersedes_id = COALESCE(EXCLUDED.supersedes_id, documents.supersedes_id),
    updated_at = now()
RETURNING id, content_hash, collection, workspace_hash
`

type UpsertDocumentParams struct {
	WorkspaceHash string
	ContentHash   string
	Title         string
	Content       string
	SourcePath    string
	Collection    string
	Tags          []string
	Metadata      pqtype.NullRawMessage
	SupersedesID  uuid.NullUUID
}

type UpsertDocumentRow struct {
	ID            uuid.UUID
	ContentHash   string
	Collection    string
	WorkspaceHash string
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (UpsertDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, upsertDocument,
		arg.WorkspaceHash,
		arg.ContentHash,
		arg.Title,
		arg.Content,
		arg.SourcePath,
		arg.Collection,
		pq.Array(arg.Tags),
		arg.Metadata,
		arg.SupersedesID,
	)
	var i UpsertDocumentRow
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.Collection,
		&i.WorkspaceHash,
	)
	return i, err
}

const upsertDocumentBySourcePath = `-- name: UpsertDocumentBySourcePath :one
INSERT INTO documents (workspace_hash, content_hash, title, content, source_path, collection, tags, metadata, supersedes_id, mod_time, file_size)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (source_path, workspace_hash) WHERE source_path != '' DO UPDATE SET
    content_hash = EXCLUDED.content_hash,
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    collection = EXCLUDED.collection,
    tags = EXCLUDED.tags,
    metadata = EXCLUDED.metadata,
    supersedes_id = COALESCE(EXCLUDED.supersedes_id, documents.supersedes_id),
    mod_time = EXCLUDED.mod_time,
    file_size = EXCLUDED.file_size,
    updated_at = now()
RETURNING id, content_hash, collection, workspace_hash
`

type UpsertDocumentBySourcePathParams struct {
	WorkspaceHash string
	ContentHash   string
	Title         string
	Content       string
	SourcePath    string
	Collection    string
	Tags          []string
	Metadata      pqtype.NullRawMessage
	SupersedesID  uuid.NullUUID
	ModTime       sql.NullTime
	FileSize      sql.NullInt64
}

type UpsertDocumentBySourcePathRow struct {
	ID            uuid.UUID
	ContentHash   string
	Collection    string
	WorkspaceHash string
}

func (q *Queries) UpsertDocumentBySourcePath(ctx context.Context, arg UpsertDocumentBySourcePathParams) (UpsertDocumentBySourcePathRow, error) {
	row := q.db.QueryRowContext(ctx, upsertDocumentBySourcePath,
		arg.WorkspaceHash,
		arg.ContentHash,
		arg.Title,
		arg.Content,
		arg.SourcePath,
		arg.Collection,
		pq.Array(arg.Tags),
		arg.Metadata,
		arg.SupersedesID,
		arg.ModTime,
		arg.FileSize,
	)
	var i UpsertDocumentBySourcePathRow
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.Collection,
		&i.WorkspaceHash,
	)
	return i, err
}
