// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const getDocumentByHash = `-- name: GetDocumentByHash :one
SELECT id, workspace_hash, content_hash, title, content, source_path, collection, tags, metadata, created_at, updated_at FROM documents WHERE content_hash = $1 AND workspace_hash = $2
`

type GetDocumentByHashParams struct {
	ContentHash   string
	WorkspaceHash string
}

func (q *Queries) GetDocumentByHash(ctx context.Context, arg GetDocumentByHashParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByHash, arg.ContentHash, arg.WorkspaceHash)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceHash,
		&i.ContentHash,
		&i.Title,
		&i.Content,
		&i.SourcePath,
		&i.Collection,
		pq.Array(&i.Tags),
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentsByWorkspace = `-- name: ListDocumentsByWorkspace :many
SELECT id, workspace_hash, content_hash, title, source_path, collection, tags, created_at, updated_at
FROM documents WHERE workspace_hash = $1 ORDER BY updated_at DESC
`

type ListDocumentsByWorkspaceRow struct {
	ID            uuid.UUID
	WorkspaceHash string
	ContentHash   string
	Title         string
	SourcePath    string
	Collection    string
	Tags          []string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListDocumentsByWorkspace(ctx context.Context, workspaceHash string) ([]ListDocumentsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByWorkspace, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByWorkspaceRow
	for rows.Next() {
		var i ListDocumentsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceHash,
			&i.ContentHash,
			&i.Title,
			&i.SourcePath,
			&i.Collection,
			pq.Array(&i.Tags),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO documents (workspace_hash, content_hash, title, content, source_path, collection, tags, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (content_hash, workspace_hash) DO UPDATE SET
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    source_path = EXCLUDED.source_path,
    collection = EXCLUDED.collection,
    tags = EXCLUDED.tags,
    metadata = EXCLUDED.metadata,
    updated_at = now()
RETURNING id, content_hash, collection, workspace_hash
`

type UpsertDocumentParams struct {
	WorkspaceHash string
	ContentHash   string
	Title         string
	Content       string
	SourcePath    string
	Collection    string
	Tags          []string
	Metadata      pqtype.NullRawMessage
}

type UpsertDocumentRow struct {
	ID            uuid.UUID
	ContentHash   string
	Collection    string
	WorkspaceHash string
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (UpsertDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, upsertDocument,
		arg.WorkspaceHash,
		arg.ContentHash,
		arg.Title,
		arg.Content,
		arg.SourcePath,
		arg.Collection,
		pq.Array(arg.Tags),
		arg.Metadata,
	)
	var i UpsertDocumentRow
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.Collection,
		&i.WorkspaceHash,
	)
	return i, err
}
