// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embeddings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
	pgvector_go "github.com/pgvector/pgvector-go"
	"github.com/sqlc-dev/pqtype"
)

const countEmbedFailedChunks = `-- name: CountEmbedFailedChunks :one
SELECT count(*) FROM chunks WHERE workspace_hash = $1 AND embed_status = 'embed_failed'
`

func (q *Queries) CountEmbedFailedChunks(ctx context.Context, workspaceHash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmbedFailedChunks, workspaceHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingChunks = `-- name: CountPendingChunks :one
SELECT count(*) FROM chunks WHERE workspace_hash = $1 AND embed_status = 'pending'
`

func (q *Queries) CountPendingChunks(ctx context.Context, workspaceHash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingChunks, workspaceHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPendingChunks = `-- name: GetPendingChunks :many
SELECT c.id, c.document_id, c.workspace_hash, c.content_hash, c.content, c.chunk_index, c.start_line, c.end_line, c.metadata, c.created_at, c.embed_status FROM chunks c
WHERE c.workspace_hash = $1
AND c.embed_status = 'pending'
ORDER BY c.created_at ASC
LIMIT $2
`

type GetPendingChunksParams struct {
	WorkspaceHash string
	Limit         int32
}

func (q *Queries) GetPendingChunks(ctx context.Context, arg GetPendingChunksParams) ([]Chunk, error) {
	rows, err := q.db.QueryContext(ctx, getPendingChunks, arg.WorkspaceHash, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chunk
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.WorkspaceHash,
			&i.ContentHash,
			&i.Content,
			&i.ChunkIndex,
			&i.StartLine,
			&i.EndLine,
			&i.Metadata,
			&i.CreatedAt,
			&i.EmbedStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEmbedding = `-- name: InsertEmbedding :one
INSERT INTO embeddings (chunk_id, workspace_hash, provider, model, embedding)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (chunk_id) DO UPDATE SET
    embedding = EXCLUDED.embedding,
    provider = EXCLUDED.provider,
    model = EXCLUDED.model,
    updated_at = now()
RETURNING id, chunk_id, workspace_hash, provider, model, embedding, created_at, updated_at
`

type InsertEmbeddingParams struct {
	ChunkID       uuid.UUID
	WorkspaceHash string
	Provider      string
	Model         string
	Embedding     interface{}
}

func (q *Queries) InsertEmbedding(ctx context.Context, arg InsertEmbeddingParams) (Embedding, error) {
	row := q.db.QueryRowContext(ctx, insertEmbedding,
		arg.ChunkID,
		arg.WorkspaceHash,
		arg.Provider,
		arg.Model,
		arg.Embedding,
	)
	var i Embedding
	err := row.Scan(
		&i.ID,
		&i.ChunkID,
		&i.WorkspaceHash,
		&i.Provider,
		&i.Model,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markChunkEmbedFailed = `-- name: MarkChunkEmbedFailed :exec
UPDATE chunks SET embed_status = 'embed_failed' WHERE id = $1 AND workspace_hash = $2
`

type MarkChunkEmbedFailedParams struct {
	ID            uuid.UUID
	WorkspaceHash string
}

func (q *Queries) MarkChunkEmbedFailed(ctx context.Context, arg MarkChunkEmbedFailedParams) error {
	_, err := q.db.ExecContext(ctx, markChunkEmbedFailed, arg.ID, arg.WorkspaceHash)
	return err
}

const markChunkEmbedded = `-- name: MarkChunkEmbedded :exec
UPDATE chunks SET embed_status = 'embedded' WHERE id = $1 AND workspace_hash = $2
`

type MarkChunkEmbeddedParams struct {
	ID            uuid.UUID
	WorkspaceHash string
}

func (q *Queries) MarkChunkEmbedded(ctx context.Context, arg MarkChunkEmbeddedParams) error {
	_, err := q.db.ExecContext(ctx, markChunkEmbedded, arg.ID, arg.WorkspaceHash)
	return err
}

const resetEmbedStatus = `-- name: ResetEmbedStatus :exec
UPDATE chunks SET embed_status = 'pending' WHERE workspace_hash = $1
`

func (q *Queries) ResetEmbedStatus(ctx context.Context, workspaceHash string) error {
	_, err := q.db.ExecContext(ctx, resetEmbedStatus, workspaceHash)
	return err
}

const vectorSearch = `-- name: VectorSearch :many
SELECT e.id, e.chunk_id, e.workspace_hash,
       c.content, c.metadata, c.document_id,
       d.source_path, d.collection, d.tags,
       CAST(1 - (e.embedding <=> $1::vector) AS double precision) AS score
FROM embeddings e
JOIN chunks c ON e.chunk_id = c.id
JOIN documents d ON c.document_id = d.id
WHERE e.workspace_hash = $2
ORDER BY e.embedding <=> $1::vector
LIMIT $3
`

type VectorSearchParams struct {
	QueryEmbedding pgvector_go.Vector
	WorkspaceHash  string
	MaxResults     int32
}

type VectorSearchRow struct {
	ID            uuid.UUID
	ChunkID       uuid.UUID
	WorkspaceHash string
	Content       string
	Metadata      pqtype.NullRawMessage
	DocumentID    uuid.UUID
	SourcePath    string
	Collection    string
	Tags          []string
	Score         float64
}

func (q *Queries) VectorSearch(ctx context.Context, arg VectorSearchParams) ([]VectorSearchRow, error) {
	rows, err := q.db.QueryContext(ctx, vectorSearch, arg.QueryEmbedding, arg.WorkspaceHash, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VectorSearchRow
	for rows.Next() {
		var i VectorSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.ChunkID,
			&i.WorkspaceHash,
			&i.Content,
			&i.Metadata,
			&i.DocumentID,
			&i.SourcePath,
			&i.Collection,
			pq.Array(&i.Tags),
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
