// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entities.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const deleteEntitiesByChunkIDs = `-- name: DeleteEntitiesByChunkIDs :exec
DELETE FROM chunk_entities WHERE chunk_id = ANY($1::uuid[])
`

func (q *Queries) DeleteEntitiesByChunkIDs(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEntitiesByChunkIDs, pq.Array(dollar_1))
	return err
}

const getChunkIDsByEntityNames = `-- name: GetChunkIDsByEntityNames :many
SELECT DISTINCT chunk_id
FROM chunk_entities
WHERE workspace_hash = $1 AND entity_name = ANY($2::text[])
`

type GetChunkIDsByEntityNamesParams struct {
	WorkspaceHash string
	Column2       []string
}

func (q *Queries) GetChunkIDsByEntityNames(ctx context.Context, arg GetChunkIDsByEntityNamesParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getChunkIDsByEntityNames, arg.WorkspaceHash, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var chunk_id uuid.UUID
		if err := rows.Scan(&chunk_id); err != nil {
			return nil, err
		}
		items = append(items, chunk_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChunkEntity = `-- name: InsertChunkEntity :exec
INSERT INTO chunk_entities (chunk_id, entity_name, entity_type, workspace_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT (chunk_id, entity_name) DO NOTHING
`

type InsertChunkEntityParams struct {
	ChunkID       uuid.UUID
	EntityName    string
	EntityType    string
	WorkspaceHash string
}

func (q *Queries) InsertChunkEntity(ctx context.Context, arg InsertChunkEntityParams) error {
	_, err := q.db.ExecContext(ctx, insertChunkEntity,
		arg.ChunkID,
		arg.EntityName,
		arg.EntityType,
		arg.WorkspaceHash,
	)
	return err
}
