// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flowcharts.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const deleteAllFunctionFlowcharts = `-- name: DeleteAllFunctionFlowcharts :exec
DELETE FROM function_flowcharts WHERE workspace_hash = $1
`

func (q *Queries) DeleteAllFunctionFlowcharts(ctx context.Context, workspaceHash string) error {
	_, err := q.db.ExecContext(ctx, deleteAllFunctionFlowcharts, workspaceHash)
	return err
}

const deleteFunctionFlowchartsByFile = `-- name: DeleteFunctionFlowchartsByFile :exec
DELETE FROM function_flowcharts WHERE workspace_hash = $1 AND source_file = $2
`

type DeleteFunctionFlowchartsByFileParams struct {
	WorkspaceHash string
	SourceFile    string
}

func (q *Queries) DeleteFunctionFlowchartsByFile(ctx context.Context, arg DeleteFunctionFlowchartsByFileParams) error {
	_, err := q.db.ExecContext(ctx, deleteFunctionFlowchartsByFile, arg.WorkspaceHash, arg.SourceFile)
	return err
}

const getFunctionFlowchart = `-- name: GetFunctionFlowchart :one
SELECT id, workspace_hash, entry, source_file, start_line, end_line, status, cfg, created_at, updated_at
FROM function_flowcharts
WHERE workspace_hash = $1 AND source_file = $2 AND start_line = $3 AND end_line = $4
`

type GetFunctionFlowchartParams struct {
	WorkspaceHash string
	SourceFile    string
	StartLine     int32
	EndLine       int32
}

func (q *Queries) GetFunctionFlowchart(ctx context.Context, arg GetFunctionFlowchartParams) (FunctionFlowchart, error) {
	row := q.db.QueryRowContext(ctx, getFunctionFlowchart,
		arg.WorkspaceHash,
		arg.SourceFile,
		arg.StartLine,
		arg.EndLine,
	)
	var i FunctionFlowchart
	err := row.Scan(
		&i.ID,
		&i.WorkspaceHash,
		&i.Entry,
		&i.SourceFile,
		&i.StartLine,
		&i.EndLine,
		&i.Status,
		&i.Cfg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFunctionFlowchartByEntry = `-- name: GetFunctionFlowchartByEntry :one
SELECT id, workspace_hash, entry, source_file, start_line, end_line, status, cfg, created_at, updated_at
FROM function_flowcharts
WHERE workspace_hash = $1 AND entry = $2
`

type GetFunctionFlowchartByEntryParams struct {
	WorkspaceHash string
	Entry         string
}

func (q *Queries) GetFunctionFlowchartByEntry(ctx context.Context, arg GetFunctionFlowchartByEntryParams) (FunctionFlowchart, error) {
	row := q.db.QueryRowContext(ctx, getFunctionFlowchartByEntry, arg.WorkspaceHash, arg.Entry)
	var i FunctionFlowchart
	err := row.Scan(
		&i.ID,
		&i.WorkspaceHash,
		&i.Entry,
		&i.SourceFile,
		&i.StartLine,
		&i.EndLine,
		&i.Status,
		&i.Cfg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFunctionFlowchartByHandler = `-- name: GetFunctionFlowchartByHandler :one
SELECT id, workspace_hash, entry, source_file, start_line, end_line, status, cfg, created_at, updated_at
FROM function_flowcharts
WHERE workspace_hash = $1
  AND (entry = $2
       OR substring(entry from '::(.*)') = $2
       OR split_part(entry, '#', 2) = $2)
ORDER BY start_line
LIMIT 1
`

type GetFunctionFlowchartByHandlerParams struct {
	WorkspaceHash string
	Entry         string
}

func (q *Queries) GetFunctionFlowchartByHandler(ctx context.Context, arg GetFunctionFlowchartByHandlerParams) (FunctionFlowchart, error) {
	row := q.db.QueryRowContext(ctx, getFunctionFlowchartByHandler, arg.WorkspaceHash, arg.Entry)
	var i FunctionFlowchart
	err := row.Scan(
		&i.ID,
		&i.WorkspaceHash,
		&i.Entry,
		&i.SourceFile,
		&i.StartLine,
		&i.EndLine,
		&i.Status,
		&i.Cfg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFunctionFlowchart = `-- name: UpsertFunctionFlowchart :exec
INSERT INTO function_flowcharts (workspace_hash, entry, source_file, start_line, end_line, status, cfg)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (workspace_hash, source_file, start_line, end_line) DO UPDATE
    SET entry = EXCLUDED.entry,
        status = EXCLUDED.status,
        cfg = EXCLUDED.cfg,
        updated_at = now()
`

type UpsertFunctionFlowchartParams struct {
	WorkspaceHash string
	Entry         string
	SourceFile    string
	StartLine     int32
	EndLine       int32
	Status        string
	Cfg           json.RawMessage
}

func (q *Queries) UpsertFunctionFlowchart(ctx context.Context, arg UpsertFunctionFlowchartParams) error {
	_, err := q.db.ExecContext(ctx, upsertFunctionFlowchart,
		arg.WorkspaceHash,
		arg.Entry,
		arg.SourceFile,
		arg.StartLine,
		arg.EndLine,
		arg.Status,
		arg.Cfg,
	)
	return err
}
