// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: graph.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const deleteGraphEdgesByFile = `-- name: DeleteGraphEdgesByFile :exec
DELETE FROM graph_edges WHERE workspace_hash = $1 AND source_file = $2
`

type DeleteGraphEdgesByFileParams struct {
	WorkspaceHash string
	SourceFile    string
}

func (q *Queries) DeleteGraphEdgesByFile(ctx context.Context, arg DeleteGraphEdgesByFileParams) error {
	_, err := q.db.ExecContext(ctx, deleteGraphEdgesByFile, arg.WorkspaceHash, arg.SourceFile)
	return err
}

const getIncomingEdges = `-- name: GetIncomingEdges :many
SELECT id, workspace_hash, source_node, target_node, edge_type, source_file, metadata, created_at
FROM graph_edges
WHERE workspace_hash = $1 AND target_node = $2
  AND ($3::text = '' OR edge_type = $3)
ORDER BY edge_type, source_node
`

type GetIncomingEdgesParams struct {
	WorkspaceHash string
	TargetNode    string
	Column3       string
}

func (q *Queries) GetIncomingEdges(ctx context.Context, arg GetIncomingEdgesParams) ([]GraphEdge, error) {
	rows, err := q.db.QueryContext(ctx, getIncomingEdges, arg.WorkspaceHash, arg.TargetNode, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GraphEdge
	for rows.Next() {
		var i GraphEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceHash,
			&i.SourceNode,
			&i.TargetNode,
			&i.EdgeType,
			&i.SourceFile,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutgoingEdges = `-- name: GetOutgoingEdges :many
SELECT id, workspace_hash, source_node, target_node, edge_type, source_file, metadata, created_at
FROM graph_edges
WHERE workspace_hash = $1 AND source_node = $2
  AND ($3::text = '' OR edge_type = $3)
ORDER BY edge_type, target_node
`

type GetOutgoingEdgesParams struct {
	WorkspaceHash string
	SourceNode    string
	Column3       string
}

func (q *Queries) GetOutgoingEdges(ctx context.Context, arg GetOutgoingEdgesParams) ([]GraphEdge, error) {
	rows, err := q.db.QueryContext(ctx, getOutgoingEdges, arg.WorkspaceHash, arg.SourceNode, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GraphEdge
	for rows.Next() {
		var i GraphEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceHash,
			&i.SourceNode,
			&i.TargetNode,
			&i.EdgeType,
			&i.SourceFile,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const graphStats = `-- name: GraphStats :one
SELECT
    COUNT(*) FILTER (WHERE edge_type = 'contains') AS contains_count,
    COUNT(*) FILTER (WHERE edge_type = 'imports')  AS imports_count,
    COUNT(*) FILTER (WHERE edge_type = 'calls')    AS calls_count
FROM graph_edges WHERE workspace_hash = $1
`

type GraphStatsRow struct {
	ContainsCount int64
	ImportsCount  int64
	CallsCount    int64
}

func (q *Queries) GraphStats(ctx context.Context, workspaceHash string) (GraphStatsRow, error) {
	row := q.db.QueryRowContext(ctx, graphStats, workspaceHash)
	var i GraphStatsRow
	err := row.Scan(&i.ContainsCount, &i.ImportsCount, &i.CallsCount)
	return i, err
}

const upsertGraphEdge = `-- name: UpsertGraphEdge :exec
INSERT INTO graph_edges (workspace_hash, source_node, target_node, edge_type, source_file, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (workspace_hash, source_node, target_node, edge_type) DO UPDATE
    SET metadata = EXCLUDED.metadata, created_at = now()
`

type UpsertGraphEdgeParams struct {
	WorkspaceHash string
	SourceNode    string
	TargetNode    string
	EdgeType      string
	SourceFile    string
	Metadata      json.RawMessage
}

func (q *Queries) UpsertGraphEdge(ctx context.Context, arg UpsertGraphEdgeParams) error {
	_, err := q.db.ExecContext(ctx, upsertGraphEdge,
		arg.WorkspaceHash,
		arg.SourceNode,
		arg.TargetNode,
		arg.EdgeType,
		arg.SourceFile,
		arg.Metadata,
	)
	return err
}
