// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Chunk struct {
	ID            uuid.UUID
	DocumentID    uuid.UUID
	WorkspaceHash string
	ContentHash   string
	Content       string
	ChunkIndex    int32
	StartLine     sql.NullInt32
	EndLine       sql.NullInt32
	Metadata      pqtype.NullRawMessage
	CreatedAt     time.Time
}

type Collection struct {
	ID              uuid.UUID
	WorkspaceHash   string
	Name            string
	Path            string
	GlobPattern     string
	UpdateMode      string
	ExcludePatterns []string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Document struct {
	ID            uuid.UUID
	WorkspaceHash string
	ContentHash   string
	Title         string
	Content       string
	SourcePath    string
	Collection    string
	Tags          []string
	Metadata      pqtype.NullRawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Embedding struct {
	ID            uuid.UUID
	ChunkID       uuid.UUID
	WorkspaceHash string
	Provider      string
	Model         string
	Embedding     interface{}
	CreatedAt     time.Time
}

type TelemetryLog struct {
	ID            uuid.UUID
	WorkspaceHash string
	EventType     string
	Payload       pqtype.NullRawMessage
	CreatedAt     time.Time
}

type Workspace struct {
	ID        uuid.UUID
	Hash      string
	Name      string
	Path      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
