// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Chunk struct {
	ID            uuid.UUID
	DocumentID    uuid.UUID
	WorkspaceHash string
	ContentHash   string
	Content       string
	ChunkIndex    int32
	StartLine     sql.NullInt32
	EndLine       sql.NullInt32
	Metadata      pqtype.NullRawMessage
	CreatedAt     time.Time
	EmbedStatus   string
	SearchVector  interface{}
}

type Collection struct {
	ID                uuid.UUID
	WorkspaceHash     string
	Name              string
	Path              string
	GlobPattern       string
	UpdateMode        string
	ExcludePatterns   []string
	AllowedExtensions []string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Document struct {
	ID            uuid.UUID
	WorkspaceHash string
	ContentHash   string
	Title         string
	Content       string
	SourcePath    string
	Collection    string
	Tags          []string
	Metadata      pqtype.NullRawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
	SupersedesID  uuid.NullUUID
}

type Embedding struct {
	ID            uuid.UUID
	ChunkID       uuid.UUID
	WorkspaceHash string
	Provider      string
	Model         string
	Embedding     interface{}
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type GraphEdge struct {
	ID            uuid.UUID
	WorkspaceHash string
	SourceNode    string
	TargetNode    string
	EdgeType      string
	SourceFile    string
	Metadata      json.RawMessage
	CreatedAt     time.Time
}

type TelemetryLog struct {
	ID            uuid.UUID
	WorkspaceHash string
	EventType     string
	Payload       pqtype.NullRawMessage
	CreatedAt     time.Time
	QueryText     string
	ResultCount   int32
	LatencyMs     int32
	Collection    string
}

type Workspace struct {
	ID        uuid.UUID
	Hash      string
	Name      string
	Path      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
