// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Chunk struct {
	ID                uuid.UUID
	DocumentID        uuid.UUID
	WorkspaceHash     string
	ContentHash       string
	Content           string
	ChunkIndex        int32
	StartLine         sql.NullInt32
	EndLine           sql.NullInt32
	Metadata          pqtype.NullRawMessage
	CreatedAt         time.Time
	EmbedStatus       string
	SearchVector      interface{}
	SymbolName        sql.NullString
	SymbolKind        sql.NullString
	Language          sql.NullString
	LineStart         sql.NullInt32
	LineEnd           sql.NullInt32
	ChunkType         string
	EmbeddingStrategy string
	Summary           sql.NullString
	SummaryHash       sql.NullString
	GraphContextHash  sql.NullString
}

type ChunkEntity struct {
	ChunkID       uuid.UUID
	EntityName    string
	EntityType    string
	WorkspaceHash string
}

type CodeSummarizationFailure struct {
	ID            uuid.UUID
	WorkspaceHash string
	SymbolName    string
	SymbolKind    sql.NullString
	SourceFile    string
	ContentHash   string
	ErrorReason   string
	ErrorType     string
	Attempts      int32
	LastAttemptAt time.Time
	ResolvedAt    sql.NullTime
	CreatedAt     time.Time
}

type CodeSummarizationUsage struct {
	WorkspaceHash string
	UsageDate     time.Time
	RequestCount  int32
}

type Collection struct {
	ID                uuid.UUID
	WorkspaceHash     string
	Name              string
	Path              string
	GlobPattern       string
	UpdateMode        string
	ExcludePatterns   []string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	AllowedExtensions []string
}

type Document struct {
	ID            uuid.UUID
	WorkspaceHash string
	ContentHash   string
	Title         string
	Content       string
	SourcePath    string
	Collection    string
	Tags          []string
	Metadata      pqtype.NullRawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
	SupersedesID  uuid.NullUUID
}

type Embedding struct {
	ID            uuid.UUID
	ChunkID       uuid.UUID
	WorkspaceHash string
	Provider      string
	Model         string
	Embedding     interface{}
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type FunctionFlowchart struct {
	ID            uuid.UUID
	WorkspaceHash string
	Entry         string
	SourceFile    string
	StartLine     int32
	EndLine       int32
	Status        string
	Cfg           json.RawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type GraphEdge struct {
	ID            uuid.UUID
	WorkspaceHash string
	SourceNode    string
	TargetNode    string
	EdgeType      string
	SourceFile    string
	Metadata      json.RawMessage
	CreatedAt     time.Time
}

type PagerankScore struct {
	WorkspaceHash string
	NodeName      string
	Score         float64
	ComputedAt    time.Time
}

type TelemetryLog struct {
	ID            uuid.UUID
	WorkspaceHash string
	EventType     string
	Payload       pqtype.NullRawMessage
	CreatedAt     time.Time
	QueryText     string
	ResultCount   int32
	LatencyMs     int32
	Collection    string
}

type Workspace struct {
	ID        uuid.UUID
	Hash      string
	Name      string
	Path      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
