// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pagerank.sql

package sqlc

import (
	"context"
)

const countCallEdges = `-- name: CountCallEdges :one
SELECT count(*)::bigint FROM graph_edges
WHERE workspace_hash = $1 AND edge_type = 'calls'
`

func (q *Queries) CountCallEdges(ctx context.Context, workspaceHash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCallEdges, workspaceHash)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deletePageRankScores = `-- name: DeletePageRankScores :exec
DELETE FROM pagerank_scores WHERE workspace_hash = $1
`

func (q *Queries) DeletePageRankScores(ctx context.Context, workspaceHash string) error {
	_, err := q.db.ExecContext(ctx, deletePageRankScores, workspaceHash)
	return err
}

const getPageRankScores = `-- name: GetPageRankScores :many
SELECT node_name, score
FROM pagerank_scores
WHERE workspace_hash = $1
`

type GetPageRankScoresRow struct {
	NodeName string
	Score    float64
}

func (q *Queries) GetPageRankScores(ctx context.Context, workspaceHash string) ([]GetPageRankScoresRow, error) {
	rows, err := q.db.QueryContext(ctx, getPageRankScores, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPageRankScoresRow
	for rows.Next() {
		var i GetPageRankScoresRow
		if err := rows.Scan(&i.NodeName, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCallEdges = `-- name: ListCallEdges :many
SELECT source_node, target_node
FROM graph_edges
WHERE workspace_hash = $1 AND edge_type = 'calls'
`

type ListCallEdgesRow struct {
	SourceNode string
	TargetNode string
}

func (q *Queries) ListCallEdges(ctx context.Context, workspaceHash string) ([]ListCallEdgesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCallEdges, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCallEdgesRow
	for rows.Next() {
		var i ListCallEdgesRow
		if err := rows.Scan(&i.SourceNode, &i.TargetNode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPageRankScore = `-- name: UpsertPageRankScore :exec
INSERT INTO pagerank_scores (workspace_hash, node_name, score, computed_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (workspace_hash, node_name) DO UPDATE
    SET score = EXCLUDED.score, computed_at = now()
`

type UpsertPageRankScoreParams struct {
	WorkspaceHash string
	NodeName      string
	Score         float64
}

func (q *Queries) UpsertPageRankScore(ctx context.Context, arg UpsertPageRankScoreParams) error {
	_, err := q.db.ExecContext(ctx, upsertPageRankScore, arg.WorkspaceHash, arg.NodeName, arg.Score)
	return err
}
