// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countBacklinksByTarget = `-- name: CountBacklinksByTarget :one
SELECT COUNT(*) FROM graph_edges
WHERE workspace_hash = $1 AND target_node = $2 AND edge_type = 'references'
`

type CountBacklinksByTargetParams struct {
	WorkspaceHash string
	TargetNode    string
}

func (q *Queries) CountBacklinksByTarget(ctx context.Context, arg CountBacklinksByTargetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBacklinksByTarget, arg.WorkspaceHash, arg.TargetNode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChunksByEmbedStatus = `-- name: CountChunksByEmbedStatus :many
SELECT c.embed_status, COUNT(*) AS chunk_count FROM chunks c
INNER JOIN documents d ON c.document_id = d.id
WHERE d.workspace_hash = $1
GROUP BY c.embed_status
`

type CountChunksByEmbedStatusRow struct {
	EmbedStatus string
	ChunkCount  int64
}

func (q *Queries) CountChunksByEmbedStatus(ctx context.Context, workspaceHash string) ([]CountChunksByEmbedStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countChunksByEmbedStatus, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountChunksByEmbedStatusRow
	for rows.Next() {
		var i CountChunksByEmbedStatusRow
		if err := rows.Scan(&i.EmbedStatus, &i.ChunkCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDocsByCollectionGrouped = `-- name: CountDocsByCollectionGrouped :many
SELECT collection, COUNT(*) AS doc_count FROM documents
WHERE workspace_hash = $1
GROUP BY collection ORDER BY doc_count DESC
`

type CountDocsByCollectionGroupedRow struct {
	Collection string
	DocCount   int64
}

func (q *Queries) CountDocsByCollectionGrouped(ctx context.Context, workspaceHash string) ([]CountDocsByCollectionGroupedRow, error) {
	rows, err := q.db.QueryContext(ctx, countDocsByCollectionGrouped, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDocsByCollectionGroupedRow
	for rows.Next() {
		var i CountDocsByCollectionGroupedRow
		if err := rows.Scan(&i.Collection, &i.DocCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGraphEdgesByType = `-- name: CountGraphEdgesByType :many
SELECT edge_type, COUNT(*) AS edge_count FROM graph_edges
WHERE workspace_hash = $1
GROUP BY edge_type
`

type CountGraphEdgesByTypeRow struct {
	EdgeType  string
	EdgeCount int64
}

func (q *Queries) CountGraphEdgesByType(ctx context.Context, workspaceHash string) ([]CountGraphEdgesByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, countGraphEdgesByType, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGraphEdgesByTypeRow
	for rows.Next() {
		var i CountGraphEdgesByTypeRow
		if err := rows.Scan(&i.EdgeType, &i.EdgeCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEdgesByNodes = `-- name: GetEdgesByNodes :many
SELECT id, workspace_hash, source_node, target_node, edge_type, source_file, metadata, created_at
FROM graph_edges
WHERE workspace_hash = $1 AND source_node = ANY($2::text[])
  AND ($3::text[] IS NULL OR edge_type = ANY($3::text[]))
ORDER BY source_node, edge_type, target_node
`

type GetEdgesByNodesParams struct {
	WorkspaceHash string
	Column2       []string
	Column3       []string
}

func (q *Queries) GetEdgesByNodes(ctx context.Context, arg GetEdgesByNodesParams) ([]GraphEdge, error) {
	rows, err := q.db.QueryContext(ctx, getEdgesByNodes, arg.WorkspaceHash, pq.Array(arg.Column2), pq.Array(arg.Column3))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GraphEdge
	for rows.Next() {
		var i GraphEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceHash,
			&i.SourceNode,
			&i.TargetNode,
			&i.EdgeType,
			&i.SourceFile,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBacklinksByTarget = `-- name: ListBacklinksByTarget :many
SELECT
  d.id, d.title, d.collection, d.updated_at, d.tags, d.content
FROM graph_edges ge
INNER JOIN documents d ON d.id::text = ge.source_node AND d.workspace_hash = ge.workspace_hash
WHERE ge.workspace_hash = $1 AND ge.target_node = $2 AND ge.edge_type = 'references'
ORDER BY d.updated_at DESC
LIMIT $3 OFFSET $4
`

type ListBacklinksByTargetParams struct {
	WorkspaceHash string
	TargetNode    string
	Limit         int32
	Offset        int32
}

type ListBacklinksByTargetRow struct {
	ID         uuid.UUID
	Title      string
	Collection string
	UpdatedAt  time.Time
	Tags       []string
	Content    string
}

func (q *Queries) ListBacklinksByTarget(ctx context.Context, arg ListBacklinksByTargetParams) ([]ListBacklinksByTargetRow, error) {
	rows, err := q.db.QueryContext(ctx, listBacklinksByTarget,
		arg.WorkspaceHash,
		arg.TargetNode,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBacklinksByTargetRow
	for rows.Next() {
		var i ListBacklinksByTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Collection,
			&i.UpdatedAt,
			pq.Array(&i.Tags),
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByIDs = `-- name: ListDocumentsByIDs :many
SELECT id, title, collection, updated_at, tags FROM documents
WHERE workspace_hash = $1 AND id = ANY($2::uuid[])
ORDER BY updated_at DESC
`

type ListDocumentsByIDsParams struct {
	WorkspaceHash string
	Column2       []uuid.UUID
}

type ListDocumentsByIDsRow struct {
	ID         uuid.UUID
	Title      string
	Collection string
	UpdatedAt  time.Time
	Tags       []string
}

func (q *Queries) ListDocumentsByIDs(ctx context.Context, arg ListDocumentsByIDsParams) ([]ListDocumentsByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByIDs, arg.WorkspaceHash, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByIDsRow
	for rows.Next() {
		var i ListDocumentsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Collection,
			&i.UpdatedAt,
			pq.Array(&i.Tags),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDocuments = `-- name: ListRecentDocuments :many
SELECT id, title, collection, updated_at, tags FROM documents
WHERE workspace_hash = $1
ORDER BY updated_at DESC LIMIT 10
`

type ListRecentDocumentsRow struct {
	ID         uuid.UUID
	Title      string
	Collection string
	UpdatedAt  time.Time
	Tags       []string
}

func (q *Queries) ListRecentDocuments(ctx context.Context, workspaceHash string) ([]ListRecentDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentDocuments, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentDocumentsRow
	for rows.Next() {
		var i ListRecentDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Collection,
			&i.UpdatedAt,
			pq.Array(&i.Tags),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentQueries = `-- name: ListRecentQueries :many
SELECT query_text, created_at FROM telemetry_logs
WHERE workspace_hash = $1 AND event_type = 'search'
ORDER BY created_at DESC LIMIT 20
`

type ListRecentQueriesRow struct {
	QueryText string
	CreatedAt time.Time
}

func (q *Queries) ListRecentQueries(ctx context.Context, workspaceHash string) ([]ListRecentQueriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentQueries, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentQueriesRow
	for rows.Next() {
		var i ListRecentQueriesRow
		if err := rows.Scan(&i.QueryText, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopTags = `-- name: ListTopTags :many
SELECT tag::text, COUNT(*) AS doc_count FROM (
  SELECT unnest(tags) AS tag FROM documents WHERE workspace_hash = $1
) t
GROUP BY tag ORDER BY doc_count DESC LIMIT 20
`

type ListTopTagsRow struct {
	Tag      string
	DocCount int64
}

func (q *Queries) ListTopTags(ctx context.Context, workspaceHash string) ([]ListTopTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopTags, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopTagsRow
	for rows.Next() {
		var i ListTopTagsRow
		if err := rows.Scan(&i.Tag, &i.DocCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
