// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telemetry.sql

package sqlc

import (
	"context"
	"database/sql"
)

const cleanupTelemetryLogs = `-- name: CleanupTelemetryLogs :execresult
DELETE FROM telemetry_logs WHERE created_at < now() - make_interval(days => $1::int)
`

func (q *Queries) CleanupTelemetryLogs(ctx context.Context, dollar_1 int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, cleanupTelemetryLogs, dollar_1)
}

const insertSearchTelemetry = `-- name: InsertSearchTelemetry :exec
INSERT INTO telemetry_logs (workspace_hash, event_type, query_text, result_count, latency_ms, collection)
VALUES ($1, 'search', $2, $3, $4, $5)
`

type InsertSearchTelemetryParams struct {
	WorkspaceHash string
	QueryText     string
	ResultCount   int32
	LatencyMs     int32
	Collection    string
}

func (q *Queries) InsertSearchTelemetry(ctx context.Context, arg InsertSearchTelemetryParams) error {
	_, err := q.db.ExecContext(ctx, insertSearchTelemetry,
		arg.WorkspaceHash,
		arg.QueryText,
		arg.ResultCount,
		arg.LatencyMs,
		arg.Collection,
	)
	return err
}
