// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wakeup.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const listCollectionsWithLastUpdated = `-- name: ListCollectionsWithLastUpdated :many
SELECT c.name,
       COALESCE(d.cnt, 0)::bigint AS document_count,
       d.last_updated
FROM collections c
LEFT JOIN (
    SELECT collection, count(*) AS cnt, max(updated_at) AS last_updated
    FROM documents doc
    WHERE doc.workspace_hash = $1
    GROUP BY collection
) d ON c.name = d.collection
WHERE c.workspace_hash = $1
ORDER BY c.name
`

type ListCollectionsWithLastUpdatedRow struct {
	Name          string
	DocumentCount int64
	LastUpdated   interface{}
}

func (q *Queries) ListCollectionsWithLastUpdated(ctx context.Context, workspaceHash string) ([]ListCollectionsWithLastUpdatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionsWithLastUpdated, workspaceHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectionsWithLastUpdatedRow
	for rows.Next() {
		var i ListCollectionsWithLastUpdatedRow
		if err := rows.Scan(&i.Name, &i.DocumentCount, &i.LastUpdated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentDocuments = `-- name: RecentDocuments :many
SELECT id, title, tags, updated_at,
       LEFT(content, 200) AS snippet
FROM documents
WHERE workspace_hash = $1
ORDER BY updated_at DESC
LIMIT $2
`

type RecentDocumentsParams struct {
	WorkspaceHash string
	Limit         int32
}

type RecentDocumentsRow struct {
	ID        uuid.UUID
	Title     string
	Tags      []string
	UpdatedAt time.Time
	Snippet   string
}

func (q *Queries) RecentDocuments(ctx context.Context, arg RecentDocumentsParams) ([]RecentDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, recentDocuments, arg.WorkspaceHash, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentDocumentsRow
	for rows.Next() {
		var i RecentDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			pq.Array(&i.Tags),
			&i.UpdatedAt,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workspaceChunkCount = `-- name: WorkspaceChunkCount :one
SELECT count(*)::bigint AS total_chunks
FROM chunks
WHERE workspace_hash = $1
`

func (q *Queries) WorkspaceChunkCount(ctx context.Context, workspaceHash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, workspaceChunkCount, workspaceHash)
	var total_chunks int64
	err := row.Scan(&total_chunks)
	return total_chunks, err
}

const workspaceDocStats = `-- name: WorkspaceDocStats :one
SELECT count(*)::bigint AS total_documents,
       max(updated_at) AS last_updated
FROM documents
WHERE workspace_hash = $1
`

type WorkspaceDocStatsRow struct {
	TotalDocuments int64
	LastUpdated    interface{}
}

func (q *Queries) WorkspaceDocStats(ctx context.Context, workspaceHash string) (WorkspaceDocStatsRow, error) {
	row := q.db.QueryRowContext(ctx, workspaceDocStats, workspaceHash)
	var i WorkspaceDocStatsRow
	err := row.Scan(&i.TotalDocuments, &i.LastUpdated)
	return i, err
}
