// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package sqlc

import (
	"context"
)

const countDocumentsByWorkspace = `-- name: CountDocumentsByWorkspace :one
SELECT COUNT(*) FROM documents WHERE workspace_hash = $1
`

func (q *Queries) CountDocumentsByWorkspace(ctx context.Context, workspaceHash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocumentsByWorkspace, workspaceHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWorkspaceByHash = `-- name: GetWorkspaceByHash :one
SELECT id, hash, name, path, created_at, updated_at FROM workspaces WHERE hash = $1
`

func (q *Queries) GetWorkspaceByHash(ctx context.Context, hash string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByHash, hash)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, hash, name, path, created_at, updated_at FROM workspaces ORDER BY name
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.Name,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkspace = `-- name: UpsertWorkspace :one
INSERT INTO workspaces (hash, name, path)
VALUES ($1, $2, $3)
ON CONFLICT (hash) DO UPDATE SET
    name = EXCLUDED.name,
    path = EXCLUDED.path,
    updated_at = now()
RETURNING id, hash, name, path, created_at, updated_at
`

type UpsertWorkspaceParams struct {
	Hash string
	Name string
	Path string
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, upsertWorkspace, arg.Hash, arg.Name, arg.Path)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
