// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countDocumentsByWorkspace = `-- name: CountDocumentsByWorkspace :one
SELECT COUNT(*) FROM documents WHERE workspace_hash = $1
`

func (q *Queries) CountDocumentsByWorkspace(ctx context.Context, workspaceHash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocumentsByWorkspace, workspaceHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrphanChunks = `-- name: CountOrphanChunks :one
SELECT COUNT(*) FROM chunks c
LEFT JOIN workspaces w ON c.workspace_hash = w.hash
WHERE w.hash IS NULL
`

func (q *Queries) CountOrphanChunks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrphanChunks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrphanDocuments = `-- name: CountOrphanDocuments :one
SELECT COUNT(*) FROM documents d
LEFT JOIN workspaces w ON d.workspace_hash = w.hash
WHERE w.hash IS NULL
`

func (q *Queries) CountOrphanDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrphanDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaces = `-- name: CountWorkspaces :one
SELECT COUNT(*) FROM workspaces
`

func (q *Queries) CountWorkspaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspacesByHashPrefix = `-- name: CountWorkspacesByHashPrefix :one
SELECT count(*) FROM workspaces WHERE hash LIKE $1
`

func (q *Queries) CountWorkspacesByHashPrefix(ctx context.Context, hash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspacesByHashPrefix, hash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOrphanChunks = `-- name: DeleteOrphanChunks :execrows
DELETE FROM chunks
WHERE workspace_hash IN (
    SELECT c.workspace_hash FROM chunks c
    LEFT JOIN workspaces w ON c.workspace_hash = w.hash
    WHERE w.hash IS NULL
)
`

func (q *Queries) DeleteOrphanChunks(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrphanChunks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOrphanDocuments = `-- name: DeleteOrphanDocuments :execrows
DELETE FROM documents
WHERE workspace_hash IN (
    SELECT d.workspace_hash FROM documents d
    LEFT JOIN workspaces w ON d.workspace_hash = w.hash
    WHERE w.hash IS NULL
)
`

func (q *Queries) DeleteOrphanDocuments(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrphanDocuments)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE hash = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, hash string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, hash)
	return err
}

const getWorkspaceByHash = `-- name: GetWorkspaceByHash :one
SELECT id, hash, name, path, created_at, updated_at FROM workspaces WHERE hash = $1
`

func (q *Queries) GetWorkspaceByHash(ctx context.Context, hash string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByHash, hash)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByHashPrefix = `-- name: GetWorkspaceByHashPrefix :one
SELECT id, hash, name, path, created_at, updated_at FROM workspaces WHERE hash LIKE $1 LIMIT 1
`

func (q *Queries) GetWorkspaceByHashPrefix(ctx context.Context, hash string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByHashPrefix, hash)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByName = `-- name: GetWorkspaceByName :one
SELECT id, hash, name, path, created_at, updated_at FROM workspaces WHERE lower(name) = lower($1)
`

func (q *Queries) GetWorkspaceByName(ctx context.Context, lower string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByName, lower)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrphanDocumentWorkspaces = `-- name: ListOrphanDocumentWorkspaces :many
SELECT d.workspace_hash AS workspace_hash, COUNT(*) AS doc_count
FROM documents d
LEFT JOIN workspaces w ON d.workspace_hash = w.hash
WHERE w.hash IS NULL
GROUP BY d.workspace_hash
ORDER BY doc_count DESC
`

type ListOrphanDocumentWorkspacesRow struct {
	WorkspaceHash string
	DocCount      int64
}

func (q *Queries) ListOrphanDocumentWorkspaces(ctx context.Context) ([]ListOrphanDocumentWorkspacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrphanDocumentWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanDocumentWorkspacesRow
	for rows.Next() {
		var i ListOrphanDocumentWorkspacesRow
		if err := rows.Scan(&i.WorkspaceHash, &i.DocCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, hash, name, path, created_at, updated_at FROM workspaces ORDER BY name
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.Name,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesWithStats = `-- name: ListWorkspacesWithStats :many
SELECT w.id, w.hash, w.name, w.path, w.created_at, w.updated_at,
    (SELECT COUNT(*) FROM documents d WHERE d.workspace_hash = w.hash) AS document_count,
    (SELECT COUNT(*) FROM chunks c WHERE c.workspace_hash = w.hash) AS chunk_count,
    (SELECT MAX(d.updated_at) FROM documents d WHERE d.workspace_hash = w.hash) AS last_document_updated
FROM workspaces w
ORDER BY w.name
`

type ListWorkspacesWithStatsRow struct {
	ID                  uuid.UUID
	Hash                string
	Name                string
	Path                string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DocumentCount       int64
	ChunkCount          int64
	LastDocumentUpdated interface{}
}

func (q *Queries) ListWorkspacesWithStats(ctx context.Context) ([]ListWorkspacesWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesWithStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspacesWithStatsRow
	for rows.Next() {
		var i ListWorkspacesWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.Name,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentCount,
			&i.ChunkCount,
			&i.LastDocumentUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkspace = `-- name: UpsertWorkspace :one
INSERT INTO workspaces (hash, name, path)
VALUES ($1, $2, $3)
ON CONFLICT (hash) DO UPDATE SET
    name = EXCLUDED.name,
    path = EXCLUDED.path,
    updated_at = now()
RETURNING id, hash, name, path, created_at, updated_at
`

type UpsertWorkspaceParams struct {
	Hash string
	Name string
	Path string
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, upsertWorkspace, arg.Hash, arg.Name, arg.Path)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
