package config

import "strings"

// RenderOpts carries the two probed substitution points the D-01..D-10
// minimal-init flow fills in before writing the config template: the
// database URL (from stepDatabase's Postgres probe/provision) and the
// embedding YAML block (from the simplified embedding probe). Every other
// section is written at its getDefaults() value, commented, with advanced
// features disabled — see fullConfigTemplate.
type RenderOpts struct {
	// DatabaseURL is substituted verbatim into the database.url field.
	DatabaseURL string
	// EmbeddingBlock is the fully-formed `embedding:\n  ...` YAML block
	// (including the leading section header), matching the shape returned
	// by stepEmbedding: either a populated ollama/voyage block or the
	// BM25-only `embedding:\n  provider: ""\n` sentinel.
	EmbeddingBlock string
}

// RenderConfig substitutes opts.DatabaseURL and opts.EmbeddingBlock into
// fullConfigTemplate and returns the resulting YAML. This is the ONLY
// supported way to produce nano-brain's default config file (D-04) —
// yaml.Marshal(getDefaults()) MUST NOT be used because the Config structs
// carry koanf/json tags but no yaml tags, so yaml.v3 lowercases field names
// and the result does not round-trip through config.Load. See
// TestRenderConfig_RoundTrip for the correctness proof.
func RenderConfig(opts RenderOpts) string {
	out := fullConfigTemplate
	// The template quotes database.url ("..."), so a DSN whose password
	// contains YAML-significant characters (#, @, :) stays a string literal.
	// Escape backslash and double-quote so the value can't break out of the
	// double-quoted scalar.
	safeURL := strings.ReplaceAll(opts.DatabaseURL, `\`, `\\`)
	safeURL = strings.ReplaceAll(safeURL, `"`, `\"`)
	out = strings.ReplaceAll(out, "{{.DatabaseURL}}", safeURL)
	out = strings.ReplaceAll(out, "{{.EmbeddingBlock}}", strings.TrimRight(opts.EmbeddingBlock, "\n"))
	return out
}

// fullConfigTemplate is the hand-authored, commented, full-config template
// (D-03/D-04). Every section from Config (internal/config/config.go)
// appears here at its getDefaults() value using the EXACT snake_case keys
// declared by the koanf struct tags — key drift between this template and
// the koanf tags is caught by TestRenderConfig_RoundTrip, which renders this
// template, loads it via config.Load, and asserts the result equals
// getDefaults() for every defaulted field.
//
// Advanced/tunable sections (summarization, code_summarization, search.hyde,
// search.reranking, search.query_preprocessing, search.entity_boost,
// search.pagerank, flow, bench, intelligence, storage, telemetry,
// watcher.exclude_patterns, bm25_language) are present but commented or
// enabled: false (D-07) — the user or an LLM agent edits this file later to
// turn them on. context_hints (D-06) is shown commented with a "written
// later per workspace" note; it is never prompted.
//
// D-05: no API key is ever written here. Each key-dependent block instead
// documents which NANO_BRAIN_* / VOYAGE_API_KEY env var enables it.
const fullConfigTemplate = `# nano-brain configuration
# Generated by "nano-brain init". Every section below is documented with its
# default value. Advanced sections are present but disabled — edit this file
# (by hand, or ask an AI agent to) to tune them. Re-run "nano-brain init" any
# time; an existing file is kept unless you choose to overwrite it.
#
# Secrets are NEVER written here — see the env var noted next to each
# key-dependent feature below.

server:
  host: localhost
  port: 3100
  auth:
    # Basic Auth gate for exposing nano-brain on a remote/VPS host. Leave
    # disabled for local-only use.
    enabled: false
    realm: nano-brain
    # users: []            # [{username: ..., password_hash: <bcrypt>}]
    # tokens: []           # bearer tokens accepted in addition to users
    bypass_paths:
      - /health
      - /api/openapi.json
  # serve_only: disables ALL background workers (embed queue, watcher,
  # harvester) so this instance only serves HTTP. Useful when running a
  # proxy container that shares a DB with a primary worker instance.
  serve_only: false

database:
  # Probed automatically by "nano-brain init" (Postgres reachable, or
  # auto-provisioned via Docker). Override with NANO_BRAIN_DATABASE_URL or
  # DATABASE_URL.
  url: "{{.DatabaseURL}}"

{{.EmbeddingBlock}}
  # VoyageAPIKey (cloud embeddings only): set VOYAGE_API_KEY env var instead
  # of writing it here.
  voyage_api_key: ""

harvester:
  # Auto-detected at init time (D-02.3) — never prompted. Leave blank to
  # disable a source.
  opencode:
    session_dir: ""
    db_path: ""
    db_root: ""
  claudecode:
    enabled: false
    session_dir: ""
    # ticket_patterns: []  # custom regexes for ticket-ID extraction
  git:
    enabled: false

intervals:
  # How often (seconds) to poll harvester sources for new sessions.
  session_poll: 120

watcher:
  # Debounce (ms) after the last file change before triggering a re-index.
  debounce_ms: 2000
  # Full re-scan interval (seconds).
  reindex_interval: 300
  chunk_overlap: 600
  # exclude_patterns: []       # glob patterns to skip when indexing
  # allowed_extensions: []     # empty = all extensions allowed
  # workspaces: {}             # per-workspace overrides, keyed by dir

search:
  # Reciprocal Rank Fusion constant (higher = smoother BM25/vector blend).
  rrf_k: 60
  # Recency boost weight (0 = off, 1 = strong boost) and half-life (days).
  recency_weight: 0.3
  recency_half_life_days: 180
  # Default max results returned per query.
  limit: 20
  # PageRank-style graph boosting — off by default, tune after your graph
  # has meaningful edge density.
  pagerank_enabled: false
  pagerank_weight: 0.2
  pagerank_edge_threshold: 100
  # Entity-mention boosting — off by default.
  entity_boost_enabled: false
  entity_boost_factor: 0.3
  # Query preprocessing (LLM query rewriting) — requires an OpenAI-compatible
  # chat endpoint. Disabled by default; set provider_url/model to enable and
  # point api_key at an env var (never write it here).
  query_preprocessing:
    enabled: false
    provider_url: ""
    api_key: ""
    model: ""
    max_latency_ms: 500
  # HyDE (Hypothetical Document Embedding) — generates a hypothetical answer
  # to embed alongside the query. Disabled by default.
  hyde:
    enabled: false
    provider_url: ""
    api_key: ""
    model: ""
    max_latency_ms: 0
    # context_hints: written later, per workspace, by you or an AI agent —
    # short domain hints that steer HyDE's hypothetical-answer generation.
    # context_hints:
    #   my-workspace-hash: "This repo is a Go REST API using sqlc + pgx."
  # Cross-encoder reranking of the fused result set — disabled by default.
  reranking:
    enabled: false
    provider: ""
    provider_url: ""
    api_key: ""
    model: ""
    top_k: 0
    max_latency_ms: 0
    min_score: 0
  bm25_language: english

storage:
  # 300MB max per file, 10GB max total collection storage.
  max_file_size: 314572800
  max_size: 10737418240

telemetry:
  retention_days: 90

logging:
  level: info
  # file: defaults to ~/.nano-brain/logs/nano-brain.log when blank.
  file: ""

# ── Advanced: disabled by default, edit to enable ──────────────────────────

summarization:
  # LLM-based session summarization. Requires an OpenAI-compatible chat
  # endpoint. Set api_key via NANO_BRAIN_SUMMARIZE_API_KEY, never here.
  enabled: false
  provider_url: ""
  api_key: ""
  model: nano-brain
  max_tokens: 8000
  concurrency: 3
  requests_per_second: 0
  output_dir: ~/.nano-brain/summaries

code_summarization:
  # LLM-based code symbol summarization. Set api_key via
  # NANO_BRAIN_CODE_SUMMARIZE_API_KEY, never here.
  enabled: false
  provider_url: ""
  api_key: ""
  model: ""
  batch_size: 30
  max_output_tokens: 8000
  concurrency: 2
  max_requests_per_day: 0
  max_symbol_lines: 500
  poll_interval_seconds: 60
  max_summaries_per_cycle: 300
  fallback_model: ""
  max_batch_tokens: 100000
  max_retries: 3
  retry_backoff_seconds: 1
  workers: 0
  request_timeout: 600

intelligence:
  # Memory consolidation / LLM categorization. Set api_key via provider's
  # standard env var convention, never here.
  enabled: false
  provider_url: ""
  api_key: ""
  model: claude-sonnet-4-5
  max_tokens: 8000
  concurrency: 3
  consolidation_age: 7

flow:
  # Execution-flow visualization (route/middleware graph extraction).
  enabled: false
  max_depth: 10
  max_fanout: 8
  summary_enabled: false
  summary_timeout: 600

bench:
  # Benchmark query generation mode: "" (default; the bench command treats
  # blank as "content" — no LLM) or "llm".
  query_generation: ""
  provider_url: ""
  api_key: ""
  model: ""
  max_tokens: 0
`
